package connections

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesResponse 
// Deprecated: This class is obsolete. Use addActivitiesPostResponse instead.
type ItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesResponse struct {
    ItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesPostResponse
}
// NewItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesResponse instantiates a new ItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesResponse and sets the default values.
func NewItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesResponse()(*ItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesResponse) {
    m := &ItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesResponse{
        ItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesPostResponse: *NewItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesPostResponse(),
    }
    return m
}
// CreateItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesResponse(), nil
}
// ItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesResponseable 
// Deprecated: This class is obsolete. Use addActivitiesPostResponse instead.
type ItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesResponseable interface {
    ItemItemsItemMicrosoftGraphExternalConnectorsAddActivitiesAddActivitiesPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
