// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package customdataprovidedresourcepayloads

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AccessReviewContextDataBase struct {
    Data
}
// NewAccessReviewContextDataBase instantiates a new AccessReviewContextDataBase and sets the default values.
func NewAccessReviewContextDataBase()(*AccessReviewContextDataBase) {
    m := &AccessReviewContextDataBase{
        Data: *NewData(),
    }
    odataTypeValue := "#microsoft.graph.customDataProvidedResourcePayloads.accessReviewContextDataBase"
    m.SetOdataType(&odataTypeValue)
    return m
}
// CreateAccessReviewContextDataBaseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAccessReviewContextDataBaseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    if parseNode != nil {
        mappingValueNode, err := parseNode.GetChildNode("@odata.type")
        if err != nil {
            return nil, err
        }
        if mappingValueNode != nil {
            mappingValue, err := mappingValueNode.GetStringValue()
            if err != nil {
                return nil, err
            }
            if mappingValue != nil {
                switch *mappingValue {
                    case "#microsoft.graph.customDataProvidedResourcePayloads.accessReviewContextData":
                        return NewAccessReviewContextData(), nil
                    case "#microsoft.graph.customDataProvidedResourcePayloads.applyDecisionContextData":
                        return NewApplyDecisionContextData(), nil
                }
            }
        }
    }
    return NewAccessReviewContextDataBase(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AccessReviewContextDataBase) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.Data.GetFieldDeserializers()
    res["reviewDefinitionId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReviewDefinitionId(val)
        }
        return nil
    }
    res["reviewInstanceId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReviewInstanceId(val)
        }
        return nil
    }
    return res
}
// GetReviewDefinitionId gets the reviewDefinitionId property value. The unique identifier of the access review definition that this data is associated with.
// returns a *string when successful
func (m *AccessReviewContextDataBase) GetReviewDefinitionId()(*string) {
    val, err := m.GetBackingStore().Get("reviewDefinitionId")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetReviewInstanceId gets the reviewInstanceId property value. The unique identifier of the access review instance that this data is associated with.
// returns a *string when successful
func (m *AccessReviewContextDataBase) GetReviewInstanceId()(*string) {
    val, err := m.GetBackingStore().Get("reviewInstanceId")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// Serialize serializes information the current object
func (m *AccessReviewContextDataBase) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.Data.Serialize(writer)
    if err != nil {
        return err
    }
    {
        err = writer.WriteStringValue("reviewDefinitionId", m.GetReviewDefinitionId())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("reviewInstanceId", m.GetReviewInstanceId())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetReviewDefinitionId sets the reviewDefinitionId property value. The unique identifier of the access review definition that this data is associated with.
func (m *AccessReviewContextDataBase) SetReviewDefinitionId(value *string)() {
    err := m.GetBackingStore().Set("reviewDefinitionId", value)
    if err != nil {
        panic(err)
    }
}
// SetReviewInstanceId sets the reviewInstanceId property value. The unique identifier of the access review instance that this data is associated with.
func (m *AccessReviewContextDataBase) SetReviewInstanceId(value *string)() {
    err := m.GetBackingStore().Set("reviewInstanceId", value)
    if err != nil {
        panic(err)
    }
}
type AccessReviewContextDataBaseable interface {
    Dataable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetReviewDefinitionId()(*string)
    GetReviewInstanceId()(*string)
    SetReviewDefinitionId(value *string)()
    SetReviewInstanceId(value *string)()
}
