// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package security

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242 "github.com/microsoftgraph/msgraph-sdk-go/models"
)

type AnalyzedEmail struct {
    iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.Entity
}
// NewAnalyzedEmail instantiates a new AnalyzedEmail and sets the default values.
func NewAnalyzedEmail()(*AnalyzedEmail) {
    m := &AnalyzedEmail{
        Entity: *iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.NewEntity(),
    }
    return m
}
// CreateAnalyzedEmailFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAnalyzedEmailFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAnalyzedEmail(), nil
}
// GetAlertIds gets the alertIds property value. A collection of values that contain the IDs of any alerts associated with the email.
// returns a []string when successful
func (m *AnalyzedEmail) GetAlertIds()([]string) {
    val, err := m.GetBackingStore().Get("alertIds")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.([]string)
    }
    return nil
}
// GetAttachments gets the attachments property value. A collection of the attachments in the email.
// returns a []AnalyzedEmailAttachmentable when successful
func (m *AnalyzedEmail) GetAttachments()([]AnalyzedEmailAttachmentable) {
    val, err := m.GetBackingStore().Get("attachments")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.([]AnalyzedEmailAttachmentable)
    }
    return nil
}
// GetAuthenticationDetails gets the authenticationDetails property value. The authentication details associated with the email.
// returns a AnalyzedEmailAuthenticationDetailable when successful
func (m *AnalyzedEmail) GetAuthenticationDetails()(AnalyzedEmailAuthenticationDetailable) {
    val, err := m.GetBackingStore().Get("authenticationDetails")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(AnalyzedEmailAuthenticationDetailable)
    }
    return nil
}
// GetBulkComplaintLevel gets the bulkComplaintLevel property value. The bulk complaint level of the email. A higher level is more likely to be spam.
// returns a *string when successful
func (m *AnalyzedEmail) GetBulkComplaintLevel()(*string) {
    val, err := m.GetBackingStore().Get("bulkComplaintLevel")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetClientType gets the clientType property value. Shows the type of client that sent the message (for example, REST).
// returns a *string when successful
func (m *AnalyzedEmail) GetClientType()(*string) {
    val, err := m.GetBackingStore().Get("clientType")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetContexts gets the contexts property value. Provides context of the email.
// returns a []string when successful
func (m *AnalyzedEmail) GetContexts()([]string) {
    val, err := m.GetBackingStore().Get("contexts")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.([]string)
    }
    return nil
}
// GetDetectionMethods gets the detectionMethods property value. The methods of detection used.
// returns a []string when successful
func (m *AnalyzedEmail) GetDetectionMethods()([]string) {
    val, err := m.GetBackingStore().Get("detectionMethods")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.([]string)
    }
    return nil
}
// GetDirectionality gets the directionality property value. The direction of the emails. The possible values are: unknown, inbound, outbound, intraOrg, unknownFutureValue.
// returns a *AntispamDirectionality when successful
func (m *AnalyzedEmail) GetDirectionality()(*AntispamDirectionality) {
    val, err := m.GetBackingStore().Get("directionality")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*AntispamDirectionality)
    }
    return nil
}
// GetDistributionList gets the distributionList property value. The distribution list details to which the email was sent.
// returns a *string when successful
func (m *AnalyzedEmail) GetDistributionList()(*string) {
    val, err := m.GetBackingStore().Get("distributionList")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetDlpRules gets the dlpRules property value. Data loss prevention rules configured in purview.
// returns a []AnalyzedEmailDlpRuleInfoable when successful
func (m *AnalyzedEmail) GetDlpRules()([]AnalyzedEmailDlpRuleInfoable) {
    val, err := m.GetBackingStore().Get("dlpRules")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.([]AnalyzedEmailDlpRuleInfoable)
    }
    return nil
}
// GetEmailClusterId gets the emailClusterId property value. The identifier for the group of similar emails clustered based on heuristic analysis of their content.
// returns a *string when successful
func (m *AnalyzedEmail) GetEmailClusterId()(*string) {
    val, err := m.GetBackingStore().Get("emailClusterId")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetExchangeTransportRules gets the exchangeTransportRules property value. The name of the Exchange transport rules (ETRs) associated with the email.
// returns a []AnalyzedEmailExchangeTransportRuleInfoable when successful
func (m *AnalyzedEmail) GetExchangeTransportRules()([]AnalyzedEmailExchangeTransportRuleInfoable) {
    val, err := m.GetBackingStore().Get("exchangeTransportRules")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.([]AnalyzedEmailExchangeTransportRuleInfoable)
    }
    return nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AnalyzedEmail) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.Entity.GetFieldDeserializers()
    res["alertIds"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetAlertIds(res)
        }
        return nil
    }
    res["attachments"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateAnalyzedEmailAttachmentFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]AnalyzedEmailAttachmentable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(AnalyzedEmailAttachmentable)
                }
            }
            m.SetAttachments(res)
        }
        return nil
    }
    res["authenticationDetails"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAnalyzedEmailAuthenticationDetailFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAuthenticationDetails(val.(AnalyzedEmailAuthenticationDetailable))
        }
        return nil
    }
    res["bulkComplaintLevel"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBulkComplaintLevel(val)
        }
        return nil
    }
    res["clientType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClientType(val)
        }
        return nil
    }
    res["contexts"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetContexts(res)
        }
        return nil
    }
    res["detectionMethods"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetDetectionMethods(res)
        }
        return nil
    }
    res["directionality"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseAntispamDirectionality)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDirectionality(val.(*AntispamDirectionality))
        }
        return nil
    }
    res["distributionList"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDistributionList(val)
        }
        return nil
    }
    res["dlpRules"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateAnalyzedEmailDlpRuleInfoFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]AnalyzedEmailDlpRuleInfoable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(AnalyzedEmailDlpRuleInfoable)
                }
            }
            m.SetDlpRules(res)
        }
        return nil
    }
    res["emailClusterId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEmailClusterId(val)
        }
        return nil
    }
    res["exchangeTransportRules"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateAnalyzedEmailExchangeTransportRuleInfoFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]AnalyzedEmailExchangeTransportRuleInfoable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(AnalyzedEmailExchangeTransportRuleInfoable)
                }
            }
            m.SetExchangeTransportRules(res)
        }
        return nil
    }
    res["forwardingDetail"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetForwardingDetail(val)
        }
        return nil
    }
    res["inboundConnectorFormattedName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInboundConnectorFormattedName(val)
        }
        return nil
    }
    res["internetMessageId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInternetMessageId(val)
        }
        return nil
    }
    res["language"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLanguage(val)
        }
        return nil
    }
    res["latestDelivery"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAnalyzedEmailDeliveryDetailFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLatestDelivery(val.(AnalyzedEmailDeliveryDetailable))
        }
        return nil
    }
    res["loggedDateTime"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLoggedDateTime(val)
        }
        return nil
    }
    res["networkMessageId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNetworkMessageId(val)
        }
        return nil
    }
    res["originalDelivery"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAnalyzedEmailDeliveryDetailFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOriginalDelivery(val.(AnalyzedEmailDeliveryDetailable))
        }
        return nil
    }
    res["overrideSources"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetOverrideSources(res)
        }
        return nil
    }
    res["phishConfidenceLevel"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPhishConfidenceLevel(val)
        }
        return nil
    }
    res["policy"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPolicy(val)
        }
        return nil
    }
    res["policyAction"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPolicyAction(val)
        }
        return nil
    }
    res["policyType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPolicyType(val)
        }
        return nil
    }
    res["primaryOverrideSource"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPrimaryOverrideSource(val)
        }
        return nil
    }
    res["recipientDetail"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAnalyzedEmailRecipientDetailFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRecipientDetail(val.(AnalyzedEmailRecipientDetailable))
        }
        return nil
    }
    res["recipientEmailAddress"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRecipientEmailAddress(val)
        }
        return nil
    }
    res["returnPath"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReturnPath(val)
        }
        return nil
    }
    res["senderDetail"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAnalyzedEmailSenderDetailFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSenderDetail(val.(AnalyzedEmailSenderDetailable))
        }
        return nil
    }
    res["sizeInBytes"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSizeInBytes(val)
        }
        return nil
    }
    res["spamConfidenceLevel"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSpamConfidenceLevel(val)
        }
        return nil
    }
    res["subject"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSubject(val)
        }
        return nil
    }
    res["threatDetectionDetails"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateThreatDetectionDetailFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ThreatDetectionDetailable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ThreatDetectionDetailable)
                }
            }
            m.SetThreatDetectionDetails(res)
        }
        return nil
    }
    res["threatTypes"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfEnumValues(ParseThreatType)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ThreatType, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*ThreatType))
                }
            }
            m.SetThreatTypes(res)
        }
        return nil
    }
    res["timelineEvents"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateTimelineEventFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]TimelineEventable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(TimelineEventable)
                }
            }
            m.SetTimelineEvents(res)
        }
        return nil
    }
    res["urls"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateAnalyzedEmailUrlFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]AnalyzedEmailUrlable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(AnalyzedEmailUrlable)
                }
            }
            m.SetUrls(res)
        }
        return nil
    }
    return res
}
// GetForwardingDetail gets the forwardingDetail property value. Email smtp forwarding details.
// returns a *string when successful
func (m *AnalyzedEmail) GetForwardingDetail()(*string) {
    val, err := m.GetBackingStore().Get("forwardingDetail")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetInboundConnectorFormattedName gets the inboundConnectorFormattedName property value. Custom instructions name that defines organizational mail flow and how the email was routed.
// returns a *string when successful
func (m *AnalyzedEmail) GetInboundConnectorFormattedName()(*string) {
    val, err := m.GetBackingStore().Get("inboundConnectorFormattedName")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetInternetMessageId gets the internetMessageId property value. A public-facing identifier for the email that is sent. The message ID is in the format specified by RFC2822.
// returns a *string when successful
func (m *AnalyzedEmail) GetInternetMessageId()(*string) {
    val, err := m.GetBackingStore().Get("internetMessageId")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetLanguage gets the language property value. The detected language of the email content.
// returns a *string when successful
func (m *AnalyzedEmail) GetLanguage()(*string) {
    val, err := m.GetBackingStore().Get("language")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetLatestDelivery gets the latestDelivery property value. The latest delivery details of the email.
// returns a AnalyzedEmailDeliveryDetailable when successful
func (m *AnalyzedEmail) GetLatestDelivery()(AnalyzedEmailDeliveryDetailable) {
    val, err := m.GetBackingStore().Get("latestDelivery")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(AnalyzedEmailDeliveryDetailable)
    }
    return nil
}
// GetLoggedDateTime gets the loggedDateTime property value. Date-time when the email record was logged.
// returns a *Time when successful
func (m *AnalyzedEmail) GetLoggedDateTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    val, err := m.GetBackingStore().Get("loggedDateTime")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    }
    return nil
}
// GetNetworkMessageId gets the networkMessageId property value. An internal identifier for the email generated by Microsoft 365.
// returns a *string when successful
func (m *AnalyzedEmail) GetNetworkMessageId()(*string) {
    val, err := m.GetBackingStore().Get("networkMessageId")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetOriginalDelivery gets the originalDelivery property value. The original delivery details of the email.
// returns a AnalyzedEmailDeliveryDetailable when successful
func (m *AnalyzedEmail) GetOriginalDelivery()(AnalyzedEmailDeliveryDetailable) {
    val, err := m.GetBackingStore().Get("originalDelivery")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(AnalyzedEmailDeliveryDetailable)
    }
    return nil
}
// GetOverrideSources gets the overrideSources property value. An aggregated list of all overrides with source on email.
// returns a []string when successful
func (m *AnalyzedEmail) GetOverrideSources()([]string) {
    val, err := m.GetBackingStore().Get("overrideSources")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.([]string)
    }
    return nil
}
// GetPhishConfidenceLevel gets the phishConfidenceLevel property value. The phish confidence level associated with the email
// returns a *string when successful
func (m *AnalyzedEmail) GetPhishConfidenceLevel()(*string) {
    val, err := m.GetBackingStore().Get("phishConfidenceLevel")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetPolicy gets the policy property value. The action policy that took effect.
// returns a *string when successful
func (m *AnalyzedEmail) GetPolicy()(*string) {
    val, err := m.GetBackingStore().Get("policy")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetPolicyAction gets the policyAction property value. The action taken on the email based on the configured policy.
// returns a *string when successful
func (m *AnalyzedEmail) GetPolicyAction()(*string) {
    val, err := m.GetBackingStore().Get("policyAction")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetPolicyType gets the policyType property value. Type of policy configured that defines the delivery action on email.
// returns a *string when successful
func (m *AnalyzedEmail) GetPolicyType()(*string) {
    val, err := m.GetBackingStore().Get("policyType")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetPrimaryOverrideSource gets the primaryOverrideSource property value. Shows the organization or user setting that altered the intended delivery location of the message (allowed instead of blocked, or blocked instead of allowed).
// returns a *string when successful
func (m *AnalyzedEmail) GetPrimaryOverrideSource()(*string) {
    val, err := m.GetBackingStore().Get("primaryOverrideSource")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetRecipientDetail gets the recipientDetail property value. Details of the recipients.
// returns a AnalyzedEmailRecipientDetailable when successful
func (m *AnalyzedEmail) GetRecipientDetail()(AnalyzedEmailRecipientDetailable) {
    val, err := m.GetBackingStore().Get("recipientDetail")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(AnalyzedEmailRecipientDetailable)
    }
    return nil
}
// GetRecipientEmailAddress gets the recipientEmailAddress property value. Contains the email address of the recipient.
// returns a *string when successful
func (m *AnalyzedEmail) GetRecipientEmailAddress()(*string) {
    val, err := m.GetBackingStore().Get("recipientEmailAddress")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetReturnPath gets the returnPath property value. A field that indicates where and how bounced emails are processed.
// returns a *string when successful
func (m *AnalyzedEmail) GetReturnPath()(*string) {
    val, err := m.GetBackingStore().Get("returnPath")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetSenderDetail gets the senderDetail property value. Sender details of the email.
// returns a AnalyzedEmailSenderDetailable when successful
func (m *AnalyzedEmail) GetSenderDetail()(AnalyzedEmailSenderDetailable) {
    val, err := m.GetBackingStore().Get("senderDetail")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(AnalyzedEmailSenderDetailable)
    }
    return nil
}
// GetSizeInBytes gets the sizeInBytes property value. Size of the email in bytes.
// returns a *int32 when successful
func (m *AnalyzedEmail) GetSizeInBytes()(*int32) {
    val, err := m.GetBackingStore().Get("sizeInBytes")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*int32)
    }
    return nil
}
// GetSpamConfidenceLevel gets the spamConfidenceLevel property value. Spam confidence of the email.
// returns a *string when successful
func (m *AnalyzedEmail) GetSpamConfidenceLevel()(*string) {
    val, err := m.GetBackingStore().Get("spamConfidenceLevel")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetSubject gets the subject property value. Subject of the email.
// returns a *string when successful
func (m *AnalyzedEmail) GetSubject()(*string) {
    val, err := m.GetBackingStore().Get("subject")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.(*string)
    }
    return nil
}
// GetThreatDetectionDetails gets the threatDetectionDetails property value. Information about threats detected in the email.
// returns a []ThreatDetectionDetailable when successful
func (m *AnalyzedEmail) GetThreatDetectionDetails()([]ThreatDetectionDetailable) {
    val, err := m.GetBackingStore().Get("threatDetectionDetails")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.([]ThreatDetectionDetailable)
    }
    return nil
}
// GetThreatTypes gets the threatTypes property value. Indicates the threat types. The possible values are: unknown, spam, malware, phish, none, unknownFutureValue.
// returns a []ThreatType when successful
func (m *AnalyzedEmail) GetThreatTypes()([]ThreatType) {
    val, err := m.GetBackingStore().Get("threatTypes")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.([]ThreatType)
    }
    return nil
}
// GetTimelineEvents gets the timelineEvents property value. Delivery and post-delivery events that happened to the email.
// returns a []TimelineEventable when successful
func (m *AnalyzedEmail) GetTimelineEvents()([]TimelineEventable) {
    val, err := m.GetBackingStore().Get("timelineEvents")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.([]TimelineEventable)
    }
    return nil
}
// GetUrls gets the urls property value. A collection of the URLs in the email.
// returns a []AnalyzedEmailUrlable when successful
func (m *AnalyzedEmail) GetUrls()([]AnalyzedEmailUrlable) {
    val, err := m.GetBackingStore().Get("urls")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.([]AnalyzedEmailUrlable)
    }
    return nil
}
// Serialize serializes information the current object
func (m *AnalyzedEmail) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.Entity.Serialize(writer)
    if err != nil {
        return err
    }
    if m.GetAlertIds() != nil {
        err = writer.WriteCollectionOfStringValues("alertIds", m.GetAlertIds())
        if err != nil {
            return err
        }
    }
    if m.GetAttachments() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetAttachments()))
        for i, v := range m.GetAttachments() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err = writer.WriteCollectionOfObjectValues("attachments", cast)
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteObjectValue("authenticationDetails", m.GetAuthenticationDetails())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("bulkComplaintLevel", m.GetBulkComplaintLevel())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("clientType", m.GetClientType())
        if err != nil {
            return err
        }
    }
    if m.GetContexts() != nil {
        err = writer.WriteCollectionOfStringValues("contexts", m.GetContexts())
        if err != nil {
            return err
        }
    }
    if m.GetDetectionMethods() != nil {
        err = writer.WriteCollectionOfStringValues("detectionMethods", m.GetDetectionMethods())
        if err != nil {
            return err
        }
    }
    if m.GetDirectionality() != nil {
        cast := (*m.GetDirectionality()).String()
        err = writer.WriteStringValue("directionality", &cast)
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("distributionList", m.GetDistributionList())
        if err != nil {
            return err
        }
    }
    if m.GetDlpRules() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetDlpRules()))
        for i, v := range m.GetDlpRules() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err = writer.WriteCollectionOfObjectValues("dlpRules", cast)
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("emailClusterId", m.GetEmailClusterId())
        if err != nil {
            return err
        }
    }
    if m.GetExchangeTransportRules() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetExchangeTransportRules()))
        for i, v := range m.GetExchangeTransportRules() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err = writer.WriteCollectionOfObjectValues("exchangeTransportRules", cast)
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("forwardingDetail", m.GetForwardingDetail())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("inboundConnectorFormattedName", m.GetInboundConnectorFormattedName())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("internetMessageId", m.GetInternetMessageId())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("language", m.GetLanguage())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteObjectValue("latestDelivery", m.GetLatestDelivery())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteTimeValue("loggedDateTime", m.GetLoggedDateTime())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("networkMessageId", m.GetNetworkMessageId())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteObjectValue("originalDelivery", m.GetOriginalDelivery())
        if err != nil {
            return err
        }
    }
    if m.GetOverrideSources() != nil {
        err = writer.WriteCollectionOfStringValues("overrideSources", m.GetOverrideSources())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("phishConfidenceLevel", m.GetPhishConfidenceLevel())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("policy", m.GetPolicy())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("policyAction", m.GetPolicyAction())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("policyType", m.GetPolicyType())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("primaryOverrideSource", m.GetPrimaryOverrideSource())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteObjectValue("recipientDetail", m.GetRecipientDetail())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("recipientEmailAddress", m.GetRecipientEmailAddress())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("returnPath", m.GetReturnPath())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteObjectValue("senderDetail", m.GetSenderDetail())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteInt32Value("sizeInBytes", m.GetSizeInBytes())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("spamConfidenceLevel", m.GetSpamConfidenceLevel())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("subject", m.GetSubject())
        if err != nil {
            return err
        }
    }
    if m.GetThreatDetectionDetails() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetThreatDetectionDetails()))
        for i, v := range m.GetThreatDetectionDetails() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err = writer.WriteCollectionOfObjectValues("threatDetectionDetails", cast)
        if err != nil {
            return err
        }
    }
    if m.GetThreatTypes() != nil {
        err = writer.WriteCollectionOfStringValues("threatTypes", SerializeThreatType(m.GetThreatTypes()))
        if err != nil {
            return err
        }
    }
    if m.GetTimelineEvents() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetTimelineEvents()))
        for i, v := range m.GetTimelineEvents() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err = writer.WriteCollectionOfObjectValues("timelineEvents", cast)
        if err != nil {
            return err
        }
    }
    if m.GetUrls() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetUrls()))
        for i, v := range m.GetUrls() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err = writer.WriteCollectionOfObjectValues("urls", cast)
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAlertIds sets the alertIds property value. A collection of values that contain the IDs of any alerts associated with the email.
func (m *AnalyzedEmail) SetAlertIds(value []string)() {
    err := m.GetBackingStore().Set("alertIds", value)
    if err != nil {
        panic(err)
    }
}
// SetAttachments sets the attachments property value. A collection of the attachments in the email.
func (m *AnalyzedEmail) SetAttachments(value []AnalyzedEmailAttachmentable)() {
    err := m.GetBackingStore().Set("attachments", value)
    if err != nil {
        panic(err)
    }
}
// SetAuthenticationDetails sets the authenticationDetails property value. The authentication details associated with the email.
func (m *AnalyzedEmail) SetAuthenticationDetails(value AnalyzedEmailAuthenticationDetailable)() {
    err := m.GetBackingStore().Set("authenticationDetails", value)
    if err != nil {
        panic(err)
    }
}
// SetBulkComplaintLevel sets the bulkComplaintLevel property value. The bulk complaint level of the email. A higher level is more likely to be spam.
func (m *AnalyzedEmail) SetBulkComplaintLevel(value *string)() {
    err := m.GetBackingStore().Set("bulkComplaintLevel", value)
    if err != nil {
        panic(err)
    }
}
// SetClientType sets the clientType property value. Shows the type of client that sent the message (for example, REST).
func (m *AnalyzedEmail) SetClientType(value *string)() {
    err := m.GetBackingStore().Set("clientType", value)
    if err != nil {
        panic(err)
    }
}
// SetContexts sets the contexts property value. Provides context of the email.
func (m *AnalyzedEmail) SetContexts(value []string)() {
    err := m.GetBackingStore().Set("contexts", value)
    if err != nil {
        panic(err)
    }
}
// SetDetectionMethods sets the detectionMethods property value. The methods of detection used.
func (m *AnalyzedEmail) SetDetectionMethods(value []string)() {
    err := m.GetBackingStore().Set("detectionMethods", value)
    if err != nil {
        panic(err)
    }
}
// SetDirectionality sets the directionality property value. The direction of the emails. The possible values are: unknown, inbound, outbound, intraOrg, unknownFutureValue.
func (m *AnalyzedEmail) SetDirectionality(value *AntispamDirectionality)() {
    err := m.GetBackingStore().Set("directionality", value)
    if err != nil {
        panic(err)
    }
}
// SetDistributionList sets the distributionList property value. The distribution list details to which the email was sent.
func (m *AnalyzedEmail) SetDistributionList(value *string)() {
    err := m.GetBackingStore().Set("distributionList", value)
    if err != nil {
        panic(err)
    }
}
// SetDlpRules sets the dlpRules property value. Data loss prevention rules configured in purview.
func (m *AnalyzedEmail) SetDlpRules(value []AnalyzedEmailDlpRuleInfoable)() {
    err := m.GetBackingStore().Set("dlpRules", value)
    if err != nil {
        panic(err)
    }
}
// SetEmailClusterId sets the emailClusterId property value. The identifier for the group of similar emails clustered based on heuristic analysis of their content.
func (m *AnalyzedEmail) SetEmailClusterId(value *string)() {
    err := m.GetBackingStore().Set("emailClusterId", value)
    if err != nil {
        panic(err)
    }
}
// SetExchangeTransportRules sets the exchangeTransportRules property value. The name of the Exchange transport rules (ETRs) associated with the email.
func (m *AnalyzedEmail) SetExchangeTransportRules(value []AnalyzedEmailExchangeTransportRuleInfoable)() {
    err := m.GetBackingStore().Set("exchangeTransportRules", value)
    if err != nil {
        panic(err)
    }
}
// SetForwardingDetail sets the forwardingDetail property value. Email smtp forwarding details.
func (m *AnalyzedEmail) SetForwardingDetail(value *string)() {
    err := m.GetBackingStore().Set("forwardingDetail", value)
    if err != nil {
        panic(err)
    }
}
// SetInboundConnectorFormattedName sets the inboundConnectorFormattedName property value. Custom instructions name that defines organizational mail flow and how the email was routed.
func (m *AnalyzedEmail) SetInboundConnectorFormattedName(value *string)() {
    err := m.GetBackingStore().Set("inboundConnectorFormattedName", value)
    if err != nil {
        panic(err)
    }
}
// SetInternetMessageId sets the internetMessageId property value. A public-facing identifier for the email that is sent. The message ID is in the format specified by RFC2822.
func (m *AnalyzedEmail) SetInternetMessageId(value *string)() {
    err := m.GetBackingStore().Set("internetMessageId", value)
    if err != nil {
        panic(err)
    }
}
// SetLanguage sets the language property value. The detected language of the email content.
func (m *AnalyzedEmail) SetLanguage(value *string)() {
    err := m.GetBackingStore().Set("language", value)
    if err != nil {
        panic(err)
    }
}
// SetLatestDelivery sets the latestDelivery property value. The latest delivery details of the email.
func (m *AnalyzedEmail) SetLatestDelivery(value AnalyzedEmailDeliveryDetailable)() {
    err := m.GetBackingStore().Set("latestDelivery", value)
    if err != nil {
        panic(err)
    }
}
// SetLoggedDateTime sets the loggedDateTime property value. Date-time when the email record was logged.
func (m *AnalyzedEmail) SetLoggedDateTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    err := m.GetBackingStore().Set("loggedDateTime", value)
    if err != nil {
        panic(err)
    }
}
// SetNetworkMessageId sets the networkMessageId property value. An internal identifier for the email generated by Microsoft 365.
func (m *AnalyzedEmail) SetNetworkMessageId(value *string)() {
    err := m.GetBackingStore().Set("networkMessageId", value)
    if err != nil {
        panic(err)
    }
}
// SetOriginalDelivery sets the originalDelivery property value. The original delivery details of the email.
func (m *AnalyzedEmail) SetOriginalDelivery(value AnalyzedEmailDeliveryDetailable)() {
    err := m.GetBackingStore().Set("originalDelivery", value)
    if err != nil {
        panic(err)
    }
}
// SetOverrideSources sets the overrideSources property value. An aggregated list of all overrides with source on email.
func (m *AnalyzedEmail) SetOverrideSources(value []string)() {
    err := m.GetBackingStore().Set("overrideSources", value)
    if err != nil {
        panic(err)
    }
}
// SetPhishConfidenceLevel sets the phishConfidenceLevel property value. The phish confidence level associated with the email
func (m *AnalyzedEmail) SetPhishConfidenceLevel(value *string)() {
    err := m.GetBackingStore().Set("phishConfidenceLevel", value)
    if err != nil {
        panic(err)
    }
}
// SetPolicy sets the policy property value. The action policy that took effect.
func (m *AnalyzedEmail) SetPolicy(value *string)() {
    err := m.GetBackingStore().Set("policy", value)
    if err != nil {
        panic(err)
    }
}
// SetPolicyAction sets the policyAction property value. The action taken on the email based on the configured policy.
func (m *AnalyzedEmail) SetPolicyAction(value *string)() {
    err := m.GetBackingStore().Set("policyAction", value)
    if err != nil {
        panic(err)
    }
}
// SetPolicyType sets the policyType property value. Type of policy configured that defines the delivery action on email.
func (m *AnalyzedEmail) SetPolicyType(value *string)() {
    err := m.GetBackingStore().Set("policyType", value)
    if err != nil {
        panic(err)
    }
}
// SetPrimaryOverrideSource sets the primaryOverrideSource property value. Shows the organization or user setting that altered the intended delivery location of the message (allowed instead of blocked, or blocked instead of allowed).
func (m *AnalyzedEmail) SetPrimaryOverrideSource(value *string)() {
    err := m.GetBackingStore().Set("primaryOverrideSource", value)
    if err != nil {
        panic(err)
    }
}
// SetRecipientDetail sets the recipientDetail property value. Details of the recipients.
func (m *AnalyzedEmail) SetRecipientDetail(value AnalyzedEmailRecipientDetailable)() {
    err := m.GetBackingStore().Set("recipientDetail", value)
    if err != nil {
        panic(err)
    }
}
// SetRecipientEmailAddress sets the recipientEmailAddress property value. Contains the email address of the recipient.
func (m *AnalyzedEmail) SetRecipientEmailAddress(value *string)() {
    err := m.GetBackingStore().Set("recipientEmailAddress", value)
    if err != nil {
        panic(err)
    }
}
// SetReturnPath sets the returnPath property value. A field that indicates where and how bounced emails are processed.
func (m *AnalyzedEmail) SetReturnPath(value *string)() {
    err := m.GetBackingStore().Set("returnPath", value)
    if err != nil {
        panic(err)
    }
}
// SetSenderDetail sets the senderDetail property value. Sender details of the email.
func (m *AnalyzedEmail) SetSenderDetail(value AnalyzedEmailSenderDetailable)() {
    err := m.GetBackingStore().Set("senderDetail", value)
    if err != nil {
        panic(err)
    }
}
// SetSizeInBytes sets the sizeInBytes property value. Size of the email in bytes.
func (m *AnalyzedEmail) SetSizeInBytes(value *int32)() {
    err := m.GetBackingStore().Set("sizeInBytes", value)
    if err != nil {
        panic(err)
    }
}
// SetSpamConfidenceLevel sets the spamConfidenceLevel property value. Spam confidence of the email.
func (m *AnalyzedEmail) SetSpamConfidenceLevel(value *string)() {
    err := m.GetBackingStore().Set("spamConfidenceLevel", value)
    if err != nil {
        panic(err)
    }
}
// SetSubject sets the subject property value. Subject of the email.
func (m *AnalyzedEmail) SetSubject(value *string)() {
    err := m.GetBackingStore().Set("subject", value)
    if err != nil {
        panic(err)
    }
}
// SetThreatDetectionDetails sets the threatDetectionDetails property value. Information about threats detected in the email.
func (m *AnalyzedEmail) SetThreatDetectionDetails(value []ThreatDetectionDetailable)() {
    err := m.GetBackingStore().Set("threatDetectionDetails", value)
    if err != nil {
        panic(err)
    }
}
// SetThreatTypes sets the threatTypes property value. Indicates the threat types. The possible values are: unknown, spam, malware, phish, none, unknownFutureValue.
func (m *AnalyzedEmail) SetThreatTypes(value []ThreatType)() {
    err := m.GetBackingStore().Set("threatTypes", value)
    if err != nil {
        panic(err)
    }
}
// SetTimelineEvents sets the timelineEvents property value. Delivery and post-delivery events that happened to the email.
func (m *AnalyzedEmail) SetTimelineEvents(value []TimelineEventable)() {
    err := m.GetBackingStore().Set("timelineEvents", value)
    if err != nil {
        panic(err)
    }
}
// SetUrls sets the urls property value. A collection of the URLs in the email.
func (m *AnalyzedEmail) SetUrls(value []AnalyzedEmailUrlable)() {
    err := m.GetBackingStore().Set("urls", value)
    if err != nil {
        panic(err)
    }
}
type AnalyzedEmailable interface {
    iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.Entityable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAlertIds()([]string)
    GetAttachments()([]AnalyzedEmailAttachmentable)
    GetAuthenticationDetails()(AnalyzedEmailAuthenticationDetailable)
    GetBulkComplaintLevel()(*string)
    GetClientType()(*string)
    GetContexts()([]string)
    GetDetectionMethods()([]string)
    GetDirectionality()(*AntispamDirectionality)
    GetDistributionList()(*string)
    GetDlpRules()([]AnalyzedEmailDlpRuleInfoable)
    GetEmailClusterId()(*string)
    GetExchangeTransportRules()([]AnalyzedEmailExchangeTransportRuleInfoable)
    GetForwardingDetail()(*string)
    GetInboundConnectorFormattedName()(*string)
    GetInternetMessageId()(*string)
    GetLanguage()(*string)
    GetLatestDelivery()(AnalyzedEmailDeliveryDetailable)
    GetLoggedDateTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetNetworkMessageId()(*string)
    GetOriginalDelivery()(AnalyzedEmailDeliveryDetailable)
    GetOverrideSources()([]string)
    GetPhishConfidenceLevel()(*string)
    GetPolicy()(*string)
    GetPolicyAction()(*string)
    GetPolicyType()(*string)
    GetPrimaryOverrideSource()(*string)
    GetRecipientDetail()(AnalyzedEmailRecipientDetailable)
    GetRecipientEmailAddress()(*string)
    GetReturnPath()(*string)
    GetSenderDetail()(AnalyzedEmailSenderDetailable)
    GetSizeInBytes()(*int32)
    GetSpamConfidenceLevel()(*string)
    GetSubject()(*string)
    GetThreatDetectionDetails()([]ThreatDetectionDetailable)
    GetThreatTypes()([]ThreatType)
    GetTimelineEvents()([]TimelineEventable)
    GetUrls()([]AnalyzedEmailUrlable)
    SetAlertIds(value []string)()
    SetAttachments(value []AnalyzedEmailAttachmentable)()
    SetAuthenticationDetails(value AnalyzedEmailAuthenticationDetailable)()
    SetBulkComplaintLevel(value *string)()
    SetClientType(value *string)()
    SetContexts(value []string)()
    SetDetectionMethods(value []string)()
    SetDirectionality(value *AntispamDirectionality)()
    SetDistributionList(value *string)()
    SetDlpRules(value []AnalyzedEmailDlpRuleInfoable)()
    SetEmailClusterId(value *string)()
    SetExchangeTransportRules(value []AnalyzedEmailExchangeTransportRuleInfoable)()
    SetForwardingDetail(value *string)()
    SetInboundConnectorFormattedName(value *string)()
    SetInternetMessageId(value *string)()
    SetLanguage(value *string)()
    SetLatestDelivery(value AnalyzedEmailDeliveryDetailable)()
    SetLoggedDateTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetNetworkMessageId(value *string)()
    SetOriginalDelivery(value AnalyzedEmailDeliveryDetailable)()
    SetOverrideSources(value []string)()
    SetPhishConfidenceLevel(value *string)()
    SetPolicy(value *string)()
    SetPolicyAction(value *string)()
    SetPolicyType(value *string)()
    SetPrimaryOverrideSource(value *string)()
    SetRecipientDetail(value AnalyzedEmailRecipientDetailable)()
    SetRecipientEmailAddress(value *string)()
    SetReturnPath(value *string)()
    SetSenderDetail(value AnalyzedEmailSenderDetailable)()
    SetSizeInBytes(value *int32)()
    SetSpamConfidenceLevel(value *string)()
    SetSubject(value *string)()
    SetThreatDetectionDetails(value []ThreatDetectionDetailable)()
    SetThreatTypes(value []ThreatType)()
    SetTimelineEvents(value []TimelineEventable)()
    SetUrls(value []AnalyzedEmailUrlable)()
}
