package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use DirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type DirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    DirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewDirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new DirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewDirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*DirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &DirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        DirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewDirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateDirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use DirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type DirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    DirectoryRoleassignmentschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
