package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use DirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type DirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    DirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewDirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new DirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewDirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*DirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &DirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        DirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewDirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateDirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use DirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type DirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    DirectoryRoleeligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
