package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use DirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type DirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    DirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewDirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new DirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewDirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*DirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &DirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        DirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewDirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateDirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use DirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type DirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    DirectoryRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
