package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use DirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type DirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    DirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewDirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new DirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewDirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*DirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &DirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        DirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewDirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateDirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use DirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type DirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    DirectoryRoleeligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
