package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// DirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type DirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse struct {
    DirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnGetResponse
}
// NewDirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse instantiates a new DirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse and sets the default values.
func NewDirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse()(*DirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse) {
    m := &DirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse{
        DirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnGetResponse: *NewDirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateDirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateDirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse(), nil
}
// DirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnResponseable 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type DirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnResponseable interface {
    DirectoryRoleAssignmentSchedulesFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
