package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use DirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type DirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    DirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewDirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new DirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewDirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*DirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &DirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        DirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewDirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateDirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use DirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type DirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    DirectoryRoleassignmentscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
