package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse struct {
    EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnGetResponse
}
// NewEntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse instantiates a new EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse and sets the default values.
func NewEntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse()(*EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse) {
    m := &EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse{
        EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnGetResponse: *NewEntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateEntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateEntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse(), nil
}
// EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponseable 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponseable interface {
    EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
