package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type EntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    EntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewEntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new EntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewEntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*EntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &EntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        EntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewEntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateEntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use EntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type EntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    EntitlementmanagementRoleassignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
