package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// EntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type EntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse struct {
    EntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponse
}
// NewEntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse instantiates a new EntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse and sets the default values.
func NewEntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse()(*EntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse) {
    m := &EntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse{
        EntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponse: *NewEntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateEntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateEntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse(), nil
}
// EntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponseable 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type EntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnResponseable interface {
    EntitlementManagementRoleAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
