package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOngetResponseable instead.
type EntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOnResponse struct {
    EntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOngetResponse
}
// NewEntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOnResponse instantiates a new EntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOnResponse and sets the default values.
func NewEntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOnResponse()(*EntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOnResponse) {
    m := &EntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOnResponse{
        EntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOngetResponse: *NewEntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOngetResponse(),
    }
    return m
}
// CreateEntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use EntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOngetResponseable instead.
type EntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOnResponseable interface {
    EntitlementManagementRoleEligibilityScheduleRequestsFilterByCurrentUserWithOngetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
