package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOngetResponseable instead.
type EntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOnResponse struct {
    EntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOngetResponse
}
// NewEntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOnResponse instantiates a new EntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOnResponse and sets the default values.
func NewEntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOnResponse()(*EntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOnResponse) {
    m := &EntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOnResponse{
        EntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOngetResponse: *NewEntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOngetResponse(),
    }
    return m
}
// CreateEntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use EntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOngetResponseable instead.
type EntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOnResponseable interface {
    EntitlementManagementRoleEligibilitySchedulesFilterByCurrentUserWithOngetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
