package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOngetResponseable instead.
type EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse struct {
    EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOngetResponse
}
// NewEntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse instantiates a new EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse and sets the default values.
func NewEntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse()(*EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse) {
    m := &EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse{
        EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOngetResponse: *NewEntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOngetResponse(),
    }
    return m
}
// CreateEntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOngetResponseable instead.
type EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOnResponseable interface {
    EntitlementManagementRoleEligibilityScheduleInstancesFilterByCurrentUserWithOngetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
