package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOngetResponseable instead.
type EntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse struct {
    EntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOngetResponse
}
// NewEntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse instantiates a new EntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse and sets the default values.
func NewEntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse()(*EntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse) {
    m := &EntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse{
        EntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOngetResponse: *NewEntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOngetResponse(),
    }
    return m
}
// CreateEntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use EntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOngetResponseable instead.
type EntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOnResponseable interface {
    EntitlementManagementRoleAssignmentSchedulesFilterByCurrentUserWithOngetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
