package rolemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type EntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    EntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewEntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new EntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewEntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*EntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &EntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        EntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewEntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateEntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use EntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type EntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    EntitlementmanagementRoleeligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
