package reports

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use GetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeGetResponseable instead.
type GetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeResponse struct {
    GetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeGetResponse
}
// NewGetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeResponse instantiates a new GetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeResponse and sets the default values.
func NewGetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeResponse()(*GetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeResponse) {
    m := &GetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeResponse{
        GetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeGetResponse: *NewGetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeGetResponse(),
    }
    return m
}
// CreateGetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeResponse(), nil
}
// Deprecated: This class is obsolete. Use GetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeGetResponseable instead.
type GetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeResponseable interface {
    GetprinterarchivedprintjobswithprinteridwithstartdatetimewithenddatetimeGetPrinterArchivedPrintJobsWithPrinterIdWithStartDateTimeWithEndDateTimeGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
