package reports

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use SecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageGetResponseable instead.
type SecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageResponse struct {
    SecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageGetResponse
}
// NewSecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageResponse instantiates a new SecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageResponse and sets the default values.
func NewSecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageResponse()(*SecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageResponse) {
    m := &SecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageResponse{
        SecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageGetResponse: *NewSecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageGetResponse(),
    }
    return m
}
// CreateSecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageResponse(), nil
}
// Deprecated: This class is obsolete. Use SecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageGetResponseable instead.
type SecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    SecurityGetattacksimulationsimulationusercoverageGetAttackSimulationSimulationUserCoverageGetResponseable
}
