package reports

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use SecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageGetResponseable instead.
type SecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageResponse struct {
    SecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageGetResponse
}
// NewSecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageResponse instantiates a new SecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageResponse and sets the default values.
func NewSecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageResponse()(*SecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageResponse) {
    m := &SecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageResponse{
        SecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageGetResponse: *NewSecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageGetResponse(),
    }
    return m
}
// CreateSecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageResponse(), nil
}
// Deprecated: This class is obsolete. Use SecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageGetResponseable instead.
type SecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    SecurityGetattacksimulationtrainingusercoverageGetAttackSimulationTrainingUserCoverageGetResponseable
}
