// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package identitygovernance

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242 "github.com/microsoftgraph/msgraph-sdk-go/models"
    ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a "github.com/microsoftgraph/msgraph-sdk-go/models/odataerrors"
)

// EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder provides operations to manage the externalOriginResourceConnectors property of the microsoft.graph.entitlementManagement entity.
type EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderDeleteRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderDeleteRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderGetQueryParameters read the properties and relationships of an externalOriginResourceConnector object.
type EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderGetQueryParameters struct {
    // Expand related entities
    Expand []string "uriparametername:\"%24expand\""
    // Select properties to be returned
    Select []string "uriparametername:\"%24select\""
}
// EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderGetQueryParameters
}
// EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderPatchRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderPatchRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewEntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderInternal instantiates a new EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder and sets the default values.
func NewEntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder) {
    m := &EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/identityGovernance/entitlementManagement/externalOriginResourceConnectors/{externalOriginResourceConnector%2Did}{?%24expand,%24select}", pathParameters),
    }
    return m
}
// NewEntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder instantiates a new EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder and sets the default values.
func NewEntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewEntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Delete delete an externalOriginResourceConnector object.
// returns a ODataError error when the service returns a 4XX or 5XX status code
// [Find more info here]
// 
// [Find more info here]: https://learn.microsoft.com/graph/api/externaloriginresourceconnector-delete?view=graph-rest-1.0
func (m *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder) Delete(ctx context.Context, requestConfiguration *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderDeleteRequestConfiguration)(error) {
    requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a.CreateODataErrorFromDiscriminatorValue,
    }
    err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
    if err != nil {
        return err
    }
    return nil
}
// Get read the properties and relationships of an externalOriginResourceConnector object.
// returns a ExternalOriginResourceConnectorable when successful
// returns a ODataError error when the service returns a 4XX or 5XX status code
// [Find more info here]
// 
// [Find more info here]: https://learn.microsoft.com/graph/api/externaloriginresourceconnector-get?view=graph-rest-1.0
func (m *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder) Get(ctx context.Context, requestConfiguration *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderGetRequestConfiguration)(iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.ExternalOriginResourceConnectorable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a.CreateODataErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CreateExternalOriginResourceConnectorFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.ExternalOriginResourceConnectorable), nil
}
// Patch update the properties of an externalOriginResourceConnector object.
// returns a ExternalOriginResourceConnectorable when successful
// returns a ODataError error when the service returns a 4XX or 5XX status code
// [Find more info here]
// 
// [Find more info here]: https://learn.microsoft.com/graph/api/externaloriginresourceconnector-update?view=graph-rest-1.0
func (m *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder) Patch(ctx context.Context, body iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.ExternalOriginResourceConnectorable, requestConfiguration *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderPatchRequestConfiguration)(iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.ExternalOriginResourceConnectorable, error) {
    requestInfo, err := m.ToPatchRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a.CreateODataErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CreateExternalOriginResourceConnectorFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.ExternalOriginResourceConnectorable), nil
}
// ToDeleteRequestInformation delete an externalOriginResourceConnector object.
// returns a *RequestInformation when successful
func (m *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderDeleteRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToGetRequestInformation read the properties and relationships of an externalOriginResourceConnector object.
// returns a *RequestInformation when successful
func (m *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToPatchRequestInformation update the properties of an externalOriginResourceConnector object.
// returns a *RequestInformation when successful
func (m *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder) ToPatchRequestInformation(ctx context.Context, body iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.ExternalOriginResourceConnectorable, requestConfiguration *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilderPatchRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.PATCH, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder when successful
func (m *EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder) WithUrl(rawUrl string)(*EntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder) {
    return NewEntitlementManagementExternalOriginResourceConnectorsExternalOriginResourceConnectorItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
