package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use AccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOngetResponseable instead.
type AccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOnResponse struct {
    AccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOngetResponse
}
// NewAccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOnResponse instantiates a new AccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOnResponse and sets the default values.
func NewAccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOnResponse()(*AccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOnResponse) {
    m := &AccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOnResponse{
        AccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOngetResponse: *NewAccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOngetResponse(),
    }
    return m
}
// CreateAccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use AccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOngetResponseable instead.
type AccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOnResponseable interface {
    AccessReviewsDefinitionsItemInstancesItemDecisionsFilterByCurrentUserWithOngetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
