package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use AccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type AccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    AccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewAccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new AccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewAccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*AccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &AccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        AccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewAccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateAccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use AccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type AccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    AccessreviewsDefinitionsItemInstancesItemDecisionsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
