package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use AccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOngetResponseable instead.
type AccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOnResponse struct {
    AccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOngetResponse
}
// NewAccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOnResponse instantiates a new AccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOnResponse and sets the default values.
func NewAccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOnResponse()(*AccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOnResponse) {
    m := &AccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOnResponse{
        AccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOngetResponse: *NewAccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOngetResponse(),
    }
    return m
}
// CreateAccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use AccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOngetResponseable instead.
type AccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOnResponseable interface {
    AccessReviewsDefinitionsItemInstancesItemStagesFilterByCurrentUserWithOngetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
