package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOngetResponseable instead.
type AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse struct {
    AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOngetResponse
}
// NewAppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse instantiates a new AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse and sets the default values.
func NewAppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse()(*AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse) {
    m := &AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse{
        AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOngetResponse: *NewAppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOngetResponse(),
    }
    return m
}
// CreateAppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOngetResponseable instead.
type AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponseable interface {
    AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOngetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
