package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse struct {
    AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnGetResponse
}
// NewAppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse instantiates a new AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse and sets the default values.
func NewAppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse()(*AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse) {
    m := &AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse{
        AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnGetResponse: *NewAppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateAppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateAppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponse(), nil
}
// AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponseable 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnResponseable interface {
    AppConsentAppConsentRequestsItemUserConsentRequestsFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
