package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use AppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type AppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    AppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewAppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new AppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewAppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*AppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &AppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        AppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewAppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreateAppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use AppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type AppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    AppconsentAppconsentrequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
