// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package identitygovernance

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242 "github.com/microsoftgraph/msgraph-sdk-go/models"
    ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a "github.com/microsoftgraph/msgraph-sdk-go/models/odataerrors"
)

// CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder provides operations to manage the uploadSessions property of the microsoft.graph.accessPackageResource entity.
type CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderGetQueryParameters the upload sessions for uploading external access data to this resource through the Bring Your Own Data (BYOD) flow.
type CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderGetQueryParameters struct {
    // Include count of items
    Count *bool "uriparametername:\"%24count\""
    // Expand related entities
    Expand []string "uriparametername:\"%24expand\""
    // Filter items by property values
    Filter *string "uriparametername:\"%24filter\""
    // Order items by property values
    Orderby []string "uriparametername:\"%24orderby\""
    // Search items by search phrases
    Search *string "uriparametername:\"%24search\""
    // Select properties to be returned
    Select []string "uriparametername:\"%24select\""
    // Skip the first n items
    Skip *int32 "uriparametername:\"%24skip\""
    // Show only the first n items
    Top *int32 "uriparametername:\"%24top\""
}
// CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderGetQueryParameters
}
// CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// ByCustomDataProvidedResourceUploadSessionId provides operations to manage the uploadSessions property of the microsoft.graph.accessPackageResource entity.
// returns a *CatalogsItemResourceScopesItemResourceUploadSessionsCustomDataProvidedResourceUploadSessionItemRequestBuilder when successful
func (m *CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder) ByCustomDataProvidedResourceUploadSessionId(customDataProvidedResourceUploadSessionId string)(*CatalogsItemResourceScopesItemResourceUploadSessionsCustomDataProvidedResourceUploadSessionItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if customDataProvidedResourceUploadSessionId != "" {
        urlTplParams["customDataProvidedResourceUploadSession%2Did"] = customDataProvidedResourceUploadSessionId
    }
    return NewCatalogsItemResourceScopesItemResourceUploadSessionsCustomDataProvidedResourceUploadSessionItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewCatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderInternal instantiates a new CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder and sets the default values.
func NewCatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder) {
    m := &CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/identityGovernance/catalogs/{accessPackageCatalog%2Did}/resourceScopes/{accessPackageResourceScope%2Did}/resource/uploadSessions{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}", pathParameters),
    }
    return m
}
// NewCatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder instantiates a new CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder and sets the default values.
func NewCatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewCatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderInternal(urlParams, requestAdapter)
}
// Count provides operations to count the resources in the collection.
// returns a *CatalogsItemResourceScopesItemResourceUploadSessionsCountRequestBuilder when successful
func (m *CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder) Count()(*CatalogsItemResourceScopesItemResourceUploadSessionsCountRequestBuilder) {
    return NewCatalogsItemResourceScopesItemResourceUploadSessionsCountRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Get the upload sessions for uploading external access data to this resource through the Bring Your Own Data (BYOD) flow.
// returns a CustomDataProvidedResourceUploadSessionCollectionResponseable when successful
// returns a ODataError error when the service returns a 4XX or 5XX status code
func (m *CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder) Get(ctx context.Context, requestConfiguration *CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderGetRequestConfiguration)(iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CustomDataProvidedResourceUploadSessionCollectionResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a.CreateODataErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CreateCustomDataProvidedResourceUploadSessionCollectionResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CustomDataProvidedResourceUploadSessionCollectionResponseable), nil
}
// Post create new navigation property to uploadSessions for identityGovernance
// returns a CustomDataProvidedResourceUploadSessionable when successful
// returns a ODataError error when the service returns a 4XX or 5XX status code
func (m *CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder) Post(ctx context.Context, body iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CustomDataProvidedResourceUploadSessionable, requestConfiguration *CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderPostRequestConfiguration)(iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CustomDataProvidedResourceUploadSessionable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a.CreateODataErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CreateCustomDataProvidedResourceUploadSessionFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CustomDataProvidedResourceUploadSessionable), nil
}
// ToGetRequestInformation the upload sessions for uploading external access data to this resource through the Bring Your Own Data (BYOD) flow.
// returns a *RequestInformation when successful
func (m *CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToPostRequestInformation create new navigation property to uploadSessions for identityGovernance
// returns a *RequestInformation when successful
func (m *CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder) ToPostRequestInformation(ctx context.Context, body iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CustomDataProvidedResourceUploadSessionable, requestConfiguration *CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder when successful
func (m *CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder) WithUrl(rawUrl string)(*CatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder) {
    return NewCatalogsItemResourceScopesItemResourceUploadSessionsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
