// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package identitygovernance

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242 "github.com/microsoftgraph/msgraph-sdk-go/models"
    ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a "github.com/microsoftgraph/msgraph-sdk-go/models/odataerrors"
)

// EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder provides operations to call the uploadFile method.
type EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewEntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilderInternal instantiates a new EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder and sets the default values.
func NewEntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder) {
    m := &EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/identityGovernance/entitlementManagement/resources/{accessPackageResource%2Did}/scopes/{accessPackageResourceScope%2Did}/resource/uploadSessions/{customDataProvidedResourceUploadSession%2Did}/uploadFile", pathParameters),
    }
    return m
}
// NewEntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder instantiates a new EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder and sets the default values.
func NewEntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewEntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilderInternal(urlParams, requestAdapter)
}
// Post upload a file in a customDataProvidedResourceUploadSession created for an accessPackageResource.
// returns a CustomDataProvidedResourceUploadSessionable when successful
// returns a ODataError error when the service returns a 4XX or 5XX status code
// [Find more info here]
// 
// [Find more info here]: https://learn.microsoft.com/graph/api/customdataprovidedresourceuploadsession-uploadfile?view=graph-rest-1.0
func (m *EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder) Post(ctx context.Context, requestConfiguration *EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilderPostRequestConfiguration)(iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CustomDataProvidedResourceUploadSessionable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a.CreateODataErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CreateCustomDataProvidedResourceUploadSessionFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CustomDataProvidedResourceUploadSessionable), nil
}
// ToPostRequestInformation upload a file in a customDataProvidedResourceUploadSession created for an accessPackageResource.
// returns a *RequestInformation when successful
func (m *EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder when successful
func (m *EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder) WithUrl(rawUrl string)(*EntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder) {
    return NewEntitlementManagementResourcesItemScopesItemResourceUploadSessionsItemUploadFileRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
