package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsPostResponseable instead.
type EntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsResponse struct {
    EntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsPostResponse
}
// NewEntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsResponse instantiates a new EntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsResponse and sets the default values.
func NewEntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsResponse()(*EntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsResponse) {
    m := &EntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsResponse{
        EntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsPostResponse: *NewEntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsPostResponse(),
    }
    return m
}
// CreateEntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsResponse(), nil
}
// Deprecated: This class is obsolete. Use EntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsPostResponseable instead.
type EntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsResponseable interface {
    EntitlementmanagementAccesspackagesItemGetapplicablepolicyrequirementsGetApplicablePolicyRequirementsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
