package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// EntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaResponse 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type EntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaResponse struct {
    EntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaGetResponse
}
// NewEntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaResponse instantiates a new EntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaResponse and sets the default values.
func NewEntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaResponse()(*EntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaResponse) {
    m := &EntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaResponse{
        EntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaGetResponse: *NewEntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaGetResponse(),
    }
    return m
}
// CreateEntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateEntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaResponse(), nil
}
// EntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaResponseable 
// Deprecated: This class is obsolete. Use deltaGetResponse instead.
type EntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaResponseable interface {
    EntitlementManagementConnectedOrganizationsItemInternalSponsorsDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
