package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use EntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOngetResponseable instead.
type EntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOnResponse struct {
    EntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOngetResponse
}
// NewEntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOnResponse instantiates a new EntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOnResponse and sets the default values.
func NewEntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOnResponse()(*EntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOnResponse) {
    m := &EntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOnResponse{
        EntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOngetResponse: *NewEntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOngetResponse(),
    }
    return m
}
// CreateEntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use EntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOngetResponseable instead.
type EntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOnResponseable interface {
    EntitlementManagementAccessPackageAssignmentApprovalsFilterByCurrentUserWithOngetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
