package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// EntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsResponse 
// Deprecated: This class is obsolete. Use getByIdsPostResponse instead.
type EntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsResponse struct {
    EntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsPostResponse
}
// NewEntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsResponse instantiates a new EntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsResponse and sets the default values.
func NewEntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsResponse()(*EntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsResponse) {
    m := &EntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsResponse{
        EntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsPostResponse: *NewEntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsPostResponse(),
    }
    return m
}
// CreateEntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateEntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsResponse(), nil
}
// EntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsResponseable 
// Deprecated: This class is obsolete. Use getByIdsPostResponse instead.
type EntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsResponseable interface {
    EntitlementManagementConnectedOrganizationsItemExternalSponsorsGetByIdsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
