package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use PrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type PrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    PrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewPrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new PrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewPrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*PrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &PrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        PrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewPrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreatePrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use PrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type PrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    PrivilegedaccessGroupAssignmentschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
}
