package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type PrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse struct {
    PrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnGetResponse
}
// NewPrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse instantiates a new PrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse and sets the default values.
func NewPrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse()(*PrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse) {
    m := &PrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse{
        PrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnGetResponse: *NewPrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreatePrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreatePrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnResponse(), nil
}
// PrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnResponseable 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type PrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    PrivilegedAccessGroupEligibilityScheduleInstancesFilterByCurrentUserWithOnGetResponseable
}
