package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use PrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type PrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    PrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewPrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new PrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewPrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*PrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &PrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        PrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewPrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreatePrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use PrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type PrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    PrivilegedaccessGroupAssignmentapprovalsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
}
