package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use PrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type PrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    PrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewPrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new PrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewPrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*PrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &PrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        PrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewPrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreatePrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use PrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type PrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    PrivilegedaccessGroupEligibilityscheduleinstancesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
}
