package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use PrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type PrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    PrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewPrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new PrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewPrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*PrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &PrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        PrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewPrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreatePrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use PrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type PrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    PrivilegedaccessGroupEligibilityschedulerequestsFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
}
