package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use PrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type PrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse struct {
    PrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse
}
// NewPrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse instantiates a new PrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse and sets the default values.
func NewPrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse()(*PrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse) {
    m := &PrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse{
        PrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse: *NewPrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreatePrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponse(), nil
}
// Deprecated: This class is obsolete. Use PrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable instead.
type PrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    PrivilegedaccessGroupEligibilityschedulesFilterbycurrentuserwithonFilterByCurrentUserWithOnGetResponseable
}
