package identitygovernance

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type PrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse struct {
    PrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponse
}
// NewPrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse instantiates a new PrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse and sets the default values.
func NewPrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse()(*PrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse) {
    m := &PrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse{
        PrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponse: *NewPrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponse(),
    }
    return m
}
// CreatePrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreatePrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnResponse(), nil
}
// PrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnResponseable 
// Deprecated: This class is obsolete. Use filterByCurrentUserWithOnGetResponse instead.
type PrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    PrivilegedAccessGroupAssignmentScheduleRequestsFilterByCurrentUserWithOnGetResponseable
}
