package directory

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FederationconfigurationsAvailableprovidertypesAvailableProviderTypesGetResponseable instead.
type FederationconfigurationsAvailableprovidertypesAvailableProviderTypesResponse struct {
    FederationconfigurationsAvailableprovidertypesAvailableProviderTypesGetResponse
}
// NewFederationconfigurationsAvailableprovidertypesAvailableProviderTypesResponse instantiates a new FederationconfigurationsAvailableprovidertypesAvailableProviderTypesResponse and sets the default values.
func NewFederationconfigurationsAvailableprovidertypesAvailableProviderTypesResponse()(*FederationconfigurationsAvailableprovidertypesAvailableProviderTypesResponse) {
    m := &FederationconfigurationsAvailableprovidertypesAvailableProviderTypesResponse{
        FederationconfigurationsAvailableprovidertypesAvailableProviderTypesGetResponse: *NewFederationconfigurationsAvailableprovidertypesAvailableProviderTypesGetResponse(),
    }
    return m
}
// CreateFederationconfigurationsAvailableprovidertypesAvailableProviderTypesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFederationconfigurationsAvailableprovidertypesAvailableProviderTypesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFederationconfigurationsAvailableprovidertypesAvailableProviderTypesResponse(), nil
}
// Deprecated: This class is obsolete. Use FederationconfigurationsAvailableprovidertypesAvailableProviderTypesGetResponseable instead.
type FederationconfigurationsAvailableprovidertypesAvailableProviderTypesResponseable interface {
    FederationconfigurationsAvailableprovidertypesAvailableProviderTypesGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
