// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package directory

import (
	"context"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
	iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242 "github.com/microsoftgraph/msgraph-sdk-go/models"
	ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a "github.com/microsoftgraph/msgraph-sdk-go/models/odataerrors"
)

// TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder provides operations to manage the governanceInvitations property of the microsoft.graph.tenantGovernance entity.
type TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderDeleteRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderDeleteRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}

// TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderGetQueryParameters get governanceInvitations from directory
type TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderGetQueryParameters struct {
	// Expand related entities
	Expand []string "uriparametername:\"%24expand\""
	// Select properties to be returned
	Select []string "uriparametername:\"%24select\""
}

// TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
	// Request query parameters
	QueryParameters *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderGetQueryParameters
}

// TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderPatchRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderPatchRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}

// NewTenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderInternal instantiates a new TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder and sets the default values.
func NewTenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder {
	m := &TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/directory/tenantGovernance/governanceInvitations/{governanceInvitation%2Did}{?%24expand,%24select}", pathParameters),
	}
	return m
}

// NewTenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder instantiates a new TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder and sets the default values.
func NewTenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewTenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderInternal(urlParams, requestAdapter)
}

// Delete delete navigation property governanceInvitations for directory
// returns a ODataError error when the service returns a 4XX or 5XX status code
func (m *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder) Delete(ctx context.Context, requestConfiguration *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderDeleteRequestConfiguration) error {
	requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"XXX": ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a.CreateODataErrorFromDiscriminatorValue,
	}
	err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
	if err != nil {
		return err
	}
	return nil
}

// Get get governanceInvitations from directory
// returns a GovernanceInvitationable when successful
// returns a ODataError error when the service returns a 4XX or 5XX status code
func (m *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder) Get(ctx context.Context, requestConfiguration *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderGetRequestConfiguration) (iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.GovernanceInvitationable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"XXX": ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a.CreateODataErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CreateGovernanceInvitationFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.GovernanceInvitationable), nil
}

// Patch update the navigation property governanceInvitations in directory
// returns a GovernanceInvitationable when successful
// returns a ODataError error when the service returns a 4XX or 5XX status code
func (m *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder) Patch(ctx context.Context, body iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.GovernanceInvitationable, requestConfiguration *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderPatchRequestConfiguration) (iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.GovernanceInvitationable, error) {
	requestInfo, err := m.ToPatchRequestInformation(ctx, body, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"XXX": ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a.CreateODataErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CreateGovernanceInvitationFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.GovernanceInvitationable), nil
}

// ToDeleteRequestInformation delete navigation property governanceInvitations for directory
// returns a *RequestInformation when successful
func (m *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderDeleteRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// ToGetRequestInformation get governanceInvitations from directory
// returns a *RequestInformation when successful
func (m *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		if requestConfiguration.QueryParameters != nil {
			requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
		}
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// ToPatchRequestInformation update the navigation property governanceInvitations in directory
// returns a *RequestInformation when successful
func (m *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder) ToPatchRequestInformation(ctx context.Context, body iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.GovernanceInvitationable, requestConfiguration *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilderPatchRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.PATCH, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
	if err != nil {
		return nil, err
	}
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder when successful
func (m *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder) WithUrl(rawUrl string) *TenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder {
	return NewTenantGovernanceGovernanceInvitationsGovernanceInvitationItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
