// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package directory

import (
	"context"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
	iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242 "github.com/microsoftgraph/msgraph-sdk-go/models"
	ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a "github.com/microsoftgraph/msgraph-sdk-go/models/odataerrors"
)

// TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder provides operations to manage the appB2BSignInActivityMetrics property of the microsoft.graph.relatedTenant entity.
type TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilderGetQueryParameters get appB2BSignInActivityMetrics from directory
type TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilderGetQueryParameters struct {
	// Expand related entities
	Expand []string "uriparametername:\"%24expand\""
	// Select properties to be returned
	Select []string "uriparametername:\"%24select\""
}

// TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilderGetRequestConfiguration struct {
	// Request headers
	Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
	// Request options
	Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
	// Request query parameters
	QueryParameters *TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilderGetQueryParameters
}

// NewTenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilderInternal instantiates a new TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder and sets the default values.
func NewTenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder {
	m := &TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/directory/tenantGovernance/relatedTenants/{relatedTenant%2Did}/appB2BSignInActivityMetrics{?%24expand,%24select}", pathParameters),
	}
	return m
}

// NewTenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder instantiates a new TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder and sets the default values.
func NewTenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewTenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilderInternal(urlParams, requestAdapter)
}

// Get get appB2BSignInActivityMetrics from directory
// returns a B2BSignInActivityMetricsable when successful
// returns a ODataError error when the service returns a 4XX or 5XX status code
func (m *TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder) Get(ctx context.Context, requestConfiguration *TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilderGetRequestConfiguration) (iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.B2BSignInActivityMetricsable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"XXX": ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a.CreateODataErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.CreateB2BSignInActivityMetricsFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(iadcd81124412c61e647227ecfc4449d8bba17de0380ddda76f641a29edf2b242.B2BSignInActivityMetricsable), nil
}

// ToGetRequestInformation get appB2BSignInActivityMetrics from directory
// returns a *RequestInformation when successful
func (m *TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilderGetRequestConfiguration) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	if requestConfiguration != nil {
		if requestConfiguration.QueryParameters != nil {
			requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
		}
		requestInfo.Headers.AddAll(requestConfiguration.Headers)
		requestInfo.AddRequestOptions(requestConfiguration.Options)
	}
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder when successful
func (m *TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder) WithUrl(rawUrl string) *TenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder {
	return NewTenantGovernanceRelatedTenantsItemAppB2BSignInActivityMetricsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
