package graph

import (
    i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55 "github.com/microsoft/kiota/abstractions/go/serialization"
)

// MessageRulePredicatesable 
type MessageRulePredicatesable interface {
    i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.AdditionalDataHolder
    i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.Parsable
    GetBodyContains()([]string)
    GetBodyOrSubjectContains()([]string)
    GetCategories()([]string)
    GetFromAddresses()([]Recipientable)
    GetHasAttachments()(*bool)
    GetHeaderContains()([]string)
    GetImportance()(*Importance)
    GetIsApprovalRequest()(*bool)
    GetIsAutomaticForward()(*bool)
    GetIsAutomaticReply()(*bool)
    GetIsEncrypted()(*bool)
    GetIsMeetingRequest()(*bool)
    GetIsMeetingResponse()(*bool)
    GetIsNonDeliveryReport()(*bool)
    GetIsPermissionControlled()(*bool)
    GetIsReadReceipt()(*bool)
    GetIsSigned()(*bool)
    GetIsVoicemail()(*bool)
    GetMessageActionFlag()(*MessageActionFlag)
    GetNotSentToMe()(*bool)
    GetRecipientContains()([]string)
    GetSenderContains()([]string)
    GetSensitivity()(*Sensitivity)
    GetSentCcMe()(*bool)
    GetSentOnlyToMe()(*bool)
    GetSentToAddresses()([]Recipientable)
    GetSentToMe()(*bool)
    GetSentToOrCcMe()(*bool)
    GetSubjectContains()([]string)
    GetWithinSizeRange()(SizeRangeable)
    SetBodyContains(value []string)()
    SetBodyOrSubjectContains(value []string)()
    SetCategories(value []string)()
    SetFromAddresses(value []Recipientable)()
    SetHasAttachments(value *bool)()
    SetHeaderContains(value []string)()
    SetImportance(value *Importance)()
    SetIsApprovalRequest(value *bool)()
    SetIsAutomaticForward(value *bool)()
    SetIsAutomaticReply(value *bool)()
    SetIsEncrypted(value *bool)()
    SetIsMeetingRequest(value *bool)()
    SetIsMeetingResponse(value *bool)()
    SetIsNonDeliveryReport(value *bool)()
    SetIsPermissionControlled(value *bool)()
    SetIsReadReceipt(value *bool)()
    SetIsSigned(value *bool)()
    SetIsVoicemail(value *bool)()
    SetMessageActionFlag(value *MessageActionFlag)()
    SetNotSentToMe(value *bool)()
    SetRecipientContains(value []string)()
    SetSenderContains(value []string)()
    SetSensitivity(value *Sensitivity)()
    SetSentCcMe(value *bool)()
    SetSentOnlyToMe(value *bool)()
    SetSentToAddresses(value []Recipientable)()
    SetSentToMe(value *bool)()
    SetSentToOrCcMe(value *bool)()
    SetSubjectContains(value []string)()
    SetWithinSizeRange(value SizeRangeable)()
}
