package graph

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55 "github.com/microsoft/kiota/abstractions/go/serialization"
)

// Messageable 
type Messageable interface {
    OutlookItemable
    i04eb5309aeaafadd28374d79c8471df9b267510b4dc2e3144c378c50f6fd7b55.Parsable
    GetAttachments()([]Attachmentable)
    GetBccRecipients()([]Recipientable)
    GetBody()(ItemBodyable)
    GetBodyPreview()(*string)
    GetCcRecipients()([]Recipientable)
    GetConversationId()(*string)
    GetConversationIndex()([]byte)
    GetExtensions()([]Extensionable)
    GetFlag()(FollowupFlagable)
    GetFrom()(Recipientable)
    GetHasAttachments()(*bool)
    GetImportance()(*Importance)
    GetInferenceClassification()(*InferenceClassificationType)
    GetInternetMessageHeaders()([]InternetMessageHeaderable)
    GetInternetMessageId()(*string)
    GetIsDeliveryReceiptRequested()(*bool)
    GetIsDraft()(*bool)
    GetIsRead()(*bool)
    GetIsReadReceiptRequested()(*bool)
    GetMultiValueExtendedProperties()([]MultiValueLegacyExtendedPropertyable)
    GetParentFolderId()(*string)
    GetReceivedDateTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetReplyTo()([]Recipientable)
    GetSender()(Recipientable)
    GetSentDateTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetSingleValueExtendedProperties()([]SingleValueLegacyExtendedPropertyable)
    GetSubject()(*string)
    GetToRecipients()([]Recipientable)
    GetUniqueBody()(ItemBodyable)
    GetWebLink()(*string)
    SetAttachments(value []Attachmentable)()
    SetBccRecipients(value []Recipientable)()
    SetBody(value ItemBodyable)()
    SetBodyPreview(value *string)()
    SetCcRecipients(value []Recipientable)()
    SetConversationId(value *string)()
    SetConversationIndex(value []byte)()
    SetExtensions(value []Extensionable)()
    SetFlag(value FollowupFlagable)()
    SetFrom(value Recipientable)()
    SetHasAttachments(value *bool)()
    SetImportance(value *Importance)()
    SetInferenceClassification(value *InferenceClassificationType)()
    SetInternetMessageHeaders(value []InternetMessageHeaderable)()
    SetInternetMessageId(value *string)()
    SetIsDeliveryReceiptRequested(value *bool)()
    SetIsDraft(value *bool)()
    SetIsRead(value *bool)()
    SetIsReadReceiptRequested(value *bool)()
    SetMultiValueExtendedProperties(value []MultiValueLegacyExtendedPropertyable)()
    SetParentFolderId(value *string)()
    SetReceivedDateTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetReplyTo(value []Recipientable)()
    SetSender(value Recipientable)()
    SetSentDateTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetSingleValueExtendedProperties(value []SingleValueLegacyExtendedPropertyable)()
    SetSubject(value *string)()
    SetToRecipients(value []Recipientable)()
    SetUniqueBody(value ItemBodyable)()
    SetWebLink(value *string)()
}
