package graph
import (
    "strings"
    "errors"
)
type RiskDetail int

const (
    NONE_RISKDETAIL RiskDetail = iota
    ADMINGENERATEDTEMPORARYPASSWORD_RISKDETAIL
    USERPERFORMEDSECUREDPASSWORDCHANGE_RISKDETAIL
    USERPERFORMEDSECUREDPASSWORDRESET_RISKDETAIL
    ADMINCONFIRMEDSIGNINSAFE_RISKDETAIL
    AICONFIRMEDSIGNINSAFE_RISKDETAIL
    USERPASSEDMFADRIVENBYRISKBASEDPOLICY_RISKDETAIL
    ADMINDISMISSEDALLRISKFORUSER_RISKDETAIL
    ADMINCONFIRMEDSIGNINCOMPROMISED_RISKDETAIL
    HIDDEN_RISKDETAIL
    ADMINCONFIRMEDUSERCOMPROMISED_RISKDETAIL
    UNKNOWNFUTUREVALUE_RISKDETAIL
)

func (i RiskDetail) String() string {
    return []string{"NONE", "ADMINGENERATEDTEMPORARYPASSWORD", "USERPERFORMEDSECUREDPASSWORDCHANGE", "USERPERFORMEDSECUREDPASSWORDRESET", "ADMINCONFIRMEDSIGNINSAFE", "AICONFIRMEDSIGNINSAFE", "USERPASSEDMFADRIVENBYRISKBASEDPOLICY", "ADMINDISMISSEDALLRISKFORUSER", "ADMINCONFIRMEDSIGNINCOMPROMISED", "HIDDEN", "ADMINCONFIRMEDUSERCOMPROMISED", "UNKNOWNFUTUREVALUE"}[i]
}
func ParseRiskDetail(v string) (interface{}, error) {
    switch strings.ToUpper(v) {
        case "NONE":
            return NONE_RISKDETAIL, nil
        case "ADMINGENERATEDTEMPORARYPASSWORD":
            return ADMINGENERATEDTEMPORARYPASSWORD_RISKDETAIL, nil
        case "USERPERFORMEDSECUREDPASSWORDCHANGE":
            return USERPERFORMEDSECUREDPASSWORDCHANGE_RISKDETAIL, nil
        case "USERPERFORMEDSECUREDPASSWORDRESET":
            return USERPERFORMEDSECUREDPASSWORDRESET_RISKDETAIL, nil
        case "ADMINCONFIRMEDSIGNINSAFE":
            return ADMINCONFIRMEDSIGNINSAFE_RISKDETAIL, nil
        case "AICONFIRMEDSIGNINSAFE":
            return AICONFIRMEDSIGNINSAFE_RISKDETAIL, nil
        case "USERPASSEDMFADRIVENBYRISKBASEDPOLICY":
            return USERPASSEDMFADRIVENBYRISKBASEDPOLICY_RISKDETAIL, nil
        case "ADMINDISMISSEDALLRISKFORUSER":
            return ADMINDISMISSEDALLRISKFORUSER_RISKDETAIL, nil
        case "ADMINCONFIRMEDSIGNINCOMPROMISED":
            return ADMINCONFIRMEDSIGNINCOMPROMISED_RISKDETAIL, nil
        case "HIDDEN":
            return HIDDEN_RISKDETAIL, nil
        case "ADMINCONFIRMEDUSERCOMPROMISED":
            return ADMINCONFIRMEDUSERCOMPROMISED_RISKDETAIL, nil
        case "UNKNOWNFUTUREVALUE":
            return UNKNOWNFUTUREVALUE_RISKDETAIL, nil
    }
    return 0, errors.New("Unknown RiskDetail value: " + v)
}
func SerializeRiskDetail(values []RiskDetail) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
