package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdGetResponseable instead.
type ItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse struct {
    ItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdGetResponse
}
// NewItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse instantiates a new ItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse and sets the default values.
func NewItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse()(*ItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse) {
    m := &ItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse{
        ItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdGetResponse: *NewItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdGetResponse(),
    }
    return m
}
// CreateItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdGetResponseable instead.
type ItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponseable interface {
    ItemSitesItemGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
