package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdgetResponseable instead.
type ItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdResponse struct {
    ItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdgetResponse
}
// NewItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdResponse instantiates a new ItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdResponse and sets the default values.
func NewItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdResponse()(*ItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdResponse) {
    m := &ItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdResponse{
        ItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdgetResponse: *NewItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdgetResponse(),
    }
    return m
}
// CreateItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdgetResponseable instead.
type ItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdResponseable interface {
    ItemSitesItemGetByPathWithPathGetApplicableContentTypesForListWithListIdgetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
