package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserGetResponseable instead.
type ItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse struct {
    ItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserGetResponse
}
// NewItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse instantiates a new ItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse and sets the default values.
func NewItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse()(*ItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse) {
    m := &ItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse{
        ItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserGetResponse: *NewItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserGetResponse(),
    }
    return m
}
// CreateItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserGetResponseable instead.
type ItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponseable interface {
    ItemCalendarAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
