package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponseable instead.
type ItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse struct {
    ItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponse
}
// NewItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse instantiates a new ItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse and sets the default values.
func NewItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse()(*ItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse) {
    m := &ItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse{
        ItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponse: *NewItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponse(),
    }
    return m
}
// CreateItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponseable instead.
type ItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponseable interface {
    ItemSitesItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
