package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponseable instead.
type ItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse struct {
    ItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponse
}
// NewItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse instantiates a new ItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse and sets the default values.
func NewItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse()(*ItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse) {
    m := &ItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse{
        ItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponse: *NewItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponse(),
    }
    return m
}
// CreateItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponseable instead.
type ItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponseable interface {
    ItemSitesItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
