package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalGetResponseable instead.
type ItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalResponse struct {
    ItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalGetResponse
}
// NewItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalResponse instantiates a new ItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalResponse and sets the default values.
func NewItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalResponse()(*ItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalResponse) {
    m := &ItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalResponse{
        ItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalGetResponse: *NewItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalGetResponse(),
    }
    return m
}
// CreateItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalGetResponseable instead.
type ItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalResponseable interface {
    ItemSitesItemGetbypathwithpathGetactivitiesbyintervalGetActivitiesByIntervalGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
