package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemTeamPermissionGrantsGetAvailableExtensionPropertiesResponse 
// Deprecated: This class is obsolete. Use getAvailableExtensionPropertiesPostResponse instead.
type ItemTeamPermissionGrantsGetAvailableExtensionPropertiesResponse struct {
    ItemTeamPermissionGrantsGetAvailableExtensionPropertiesPostResponse
}
// NewItemTeamPermissionGrantsGetAvailableExtensionPropertiesResponse instantiates a new ItemTeamPermissionGrantsGetAvailableExtensionPropertiesResponse and sets the default values.
func NewItemTeamPermissionGrantsGetAvailableExtensionPropertiesResponse()(*ItemTeamPermissionGrantsGetAvailableExtensionPropertiesResponse) {
    m := &ItemTeamPermissionGrantsGetAvailableExtensionPropertiesResponse{
        ItemTeamPermissionGrantsGetAvailableExtensionPropertiesPostResponse: *NewItemTeamPermissionGrantsGetAvailableExtensionPropertiesPostResponse(),
    }
    return m
}
// CreateItemTeamPermissionGrantsGetAvailableExtensionPropertiesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemTeamPermissionGrantsGetAvailableExtensionPropertiesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemTeamPermissionGrantsGetAvailableExtensionPropertiesResponse(), nil
}
// ItemTeamPermissionGrantsGetAvailableExtensionPropertiesResponseable 
// Deprecated: This class is obsolete. Use getAvailableExtensionPropertiesPostResponse instead.
type ItemTeamPermissionGrantsGetAvailableExtensionPropertiesResponseable interface {
    ItemTeamPermissionGrantsGetAvailableExtensionPropertiesPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
