package groups

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesgetResponseable instead.
type ItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesResponse struct {
    ItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesgetResponse
}
// NewItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesResponse instantiates a new ItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesResponse and sets the default values.
func NewItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesResponse()(*ItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesResponse) {
    m := &ItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesResponse{
        ItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesgetResponse: *NewItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesgetResponse(),
    }
    return m
}
// CreateItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesgetResponseable instead.
type ItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesResponseable interface {
    ItemSitesItemListsItemContentTypesGetCompatibleHubContentTypesgetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
