package solutions

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use VirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleGetResponseable instead.
type VirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleResponse struct {
    VirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleGetResponse
}
// NewVirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleResponse instantiates a new VirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleResponse and sets the default values.
func NewVirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleResponse()(*VirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleResponse) {
    m := &VirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleResponse{
        VirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleGetResponse: *NewVirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleGetResponse(),
    }
    return m
}
// CreateVirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewVirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleResponse(), nil
}
// Deprecated: This class is obsolete. Use VirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleGetResponseable instead.
type VirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    VirtualeventsWebinarsGetbyuseridandrolewithuseridwithroleGetByUserIdAndRoleWithUserIdWithRoleGetResponseable
}
