package serviceprincipals

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsGetResponseable instead.
type ItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsResponse struct {
    ItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsGetResponse
}
// NewItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsResponse instantiates a new ItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsResponse and sets the default values.
func NewItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsResponse()(*ItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsResponse) {
    m := &ItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsResponse{
        ItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsGetResponse: *NewItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsGetResponse(),
    }
    return m
}
// CreateItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsGetResponseable instead.
type ItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsResponseable interface {
    ItemSynchronizationTemplatesItemSchemaFilteroperatorsFilterOperatorsGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
