package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemWorkbookTablesCountGetResponseable instead.
type FileStorageContainersItemDriveItemsItemWorkbookTablesCountResponse struct {
    FileStorageContainersItemDriveItemsItemWorkbookTablesCountGetResponse
}
// NewFileStorageContainersItemDriveItemsItemWorkbookTablesCountResponse instantiates a new FileStorageContainersItemDriveItemsItemWorkbookTablesCountResponse and sets the default values.
func NewFileStorageContainersItemDriveItemsItemWorkbookTablesCountResponse()(*FileStorageContainersItemDriveItemsItemWorkbookTablesCountResponse) {
    m := &FileStorageContainersItemDriveItemsItemWorkbookTablesCountResponse{
        FileStorageContainersItemDriveItemsItemWorkbookTablesCountGetResponse: *NewFileStorageContainersItemDriveItemsItemWorkbookTablesCountGetResponse(),
    }
    return m
}
// CreateFileStorageContainersItemDriveItemsItemWorkbookTablesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageContainersItemDriveItemsItemWorkbookTablesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageContainersItemDriveItemsItemWorkbookTablesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemWorkbookTablesCountGetResponseable instead.
type FileStorageContainersItemDriveItemsItemWorkbookTablesCountResponseable interface {
    FileStorageContainersItemDriveItemsItemWorkbookTablesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
