package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountGetResponseable instead.
type FileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse struct {
    FileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountGetResponse
}
// NewFileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse instantiates a new FileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse and sets the default values.
func NewFileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse()(*FileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse) {
    m := &FileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse{
        FileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountGetResponse: *NewFileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountGetResponse(),
    }
    return m
}
// CreateFileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountGetResponseable instead.
type FileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountResponseable interface {
    FileStorageContainersItemDriveItemsItemWorkbookTablesItemColumnsCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
