package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountResponse struct {
    FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountGetResponse
}
// NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountResponse instantiates a new FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountResponse and sets the default values.
func NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountResponse()(*FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountResponse) {
    m := &FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountResponse{
        FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountGetResponse: *NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountGetResponse(),
    }
    return m
}
// CreateFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountResponseable interface {
    FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemSeriesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
