package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemSearchwithqSearchWithQGetResponseable instead.
type FilestorageContainersItemDriveItemsItemSearchwithqSearchWithQResponse struct {
    FilestorageContainersItemDriveItemsItemSearchwithqSearchWithQGetResponse
}
// NewFilestorageContainersItemDriveItemsItemSearchwithqSearchWithQResponse instantiates a new FilestorageContainersItemDriveItemsItemSearchwithqSearchWithQResponse and sets the default values.
func NewFilestorageContainersItemDriveItemsItemSearchwithqSearchWithQResponse()(*FilestorageContainersItemDriveItemsItemSearchwithqSearchWithQResponse) {
    m := &FilestorageContainersItemDriveItemsItemSearchwithqSearchWithQResponse{
        FilestorageContainersItemDriveItemsItemSearchwithqSearchWithQGetResponse: *NewFilestorageContainersItemDriveItemsItemSearchwithqSearchWithQGetResponse(),
    }
    return m
}
// CreateFilestorageContainersItemDriveItemsItemSearchwithqSearchWithQResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageContainersItemDriveItemsItemSearchwithqSearchWithQResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageContainersItemDriveItemsItemSearchwithqSearchWithQResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemSearchwithqSearchWithQGetResponseable instead.
type FilestorageContainersItemDriveItemsItemSearchwithqSearchWithQResponseable interface {
    FilestorageContainersItemDriveItemsItemSearchwithqSearchWithQGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
