package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponseable instead.
type FilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse struct {
    FilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponse
}
// NewFilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse instantiates a new FilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse and sets the default values.
func NewFilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse()(*FilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse) {
    m := &FilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse{
        FilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponse: *NewFilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponse(),
    }
    return m
}
// CreateFilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponseable instead.
type FilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponseable interface {
    FilestorageContainersItemDriveListItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
