package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookTablesCountGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookTablesCountResponse struct {
    FilestorageContainersItemDriveItemsItemWorkbookTablesCountGetResponse
}
// NewFilestorageContainersItemDriveItemsItemWorkbookTablesCountResponse instantiates a new FilestorageContainersItemDriveItemsItemWorkbookTablesCountResponse and sets the default values.
func NewFilestorageContainersItemDriveItemsItemWorkbookTablesCountResponse()(*FilestorageContainersItemDriveItemsItemWorkbookTablesCountResponse) {
    m := &FilestorageContainersItemDriveItemsItemWorkbookTablesCountResponse{
        FilestorageContainersItemDriveItemsItemWorkbookTablesCountGetResponse: *NewFilestorageContainersItemDriveItemsItemWorkbookTablesCountGetResponse(),
    }
    return m
}
// CreateFilestorageContainersItemDriveItemsItemWorkbookTablesCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageContainersItemDriveItemsItemWorkbookTablesCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageContainersItemDriveItemsItemWorkbookTablesCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookTablesCountGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookTablesCountResponseable interface {
    FilestorageContainersItemDriveItemsItemWorkbookTablesCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
