package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenGetResponseable instead.
type FilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse struct {
    FilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenGetResponse
}
// NewFilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse instantiates a new FilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse and sets the default values.
func NewFilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse()(*FilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse) {
    m := &FilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse{
        FilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenGetResponse: *NewFilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenGetResponse(),
    }
    return m
}
// CreateFilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenGetResponseable instead.
type FilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenResponseable interface {
    FilestorageContainersItemDriveItemsItemDeltawithtokenDeltaWithTokenGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
