package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightResponse struct {
    FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightGetResponse
}
// NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightResponse instantiates a new FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightResponse and sets the default values.
func NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightResponse()(*FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightResponse) {
    m := &FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightResponse{
        FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightGetResponse: *NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightGetResponse(),
    }
    return m
}
// CreateFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightResponseable interface {
    FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImagewithwidthwithheightImageWithWidthWithHeightGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
