package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponseable instead.
type FilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse struct {
    FilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponse
}
// NewFilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse instantiates a new FilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse and sets the default values.
func NewFilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse()(*FilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse) {
    m := &FilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse{
        FilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponse: *NewFilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponse(),
    }
    return m
}
// CreateFilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponseable instead.
type FilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponseable interface {
    FilestorageContainersItemDriveItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
