package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse struct {
    FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageGetResponse
}
// NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse instantiates a new FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse and sets the default values.
func NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse()(*FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse) {
    m := &FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse{
        FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageGetResponse: *NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageGetResponse(),
    }
    return m
}
// CreateFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponseable interface {
    FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemChartsItemwithnameImageGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
