package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse struct {
    FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountGetResponse
}
// NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse instantiates a new FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse and sets the default values.
func NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse()(*FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse) {
    m := &FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse{
        FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountGetResponse: *NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountGetResponse(),
    }
    return m
}
// CreateFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponse(), nil
}
// Deprecated: This class is obsolete. Use FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountGetResponseable instead.
type FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountResponseable interface {
    FilestorageContainersItemDriveItemsItemWorkbookWorksheetsItemTablesItemRowsCountGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
