package storage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemGetActivitiesByIntervalGetResponseable instead.
type FileStorageContainersItemDriveItemsItemGetActivitiesByIntervalResponse struct {
    FileStorageContainersItemDriveItemsItemGetActivitiesByIntervalGetResponse
}
// NewFileStorageContainersItemDriveItemsItemGetActivitiesByIntervalResponse instantiates a new FileStorageContainersItemDriveItemsItemGetActivitiesByIntervalResponse and sets the default values.
func NewFileStorageContainersItemDriveItemsItemGetActivitiesByIntervalResponse()(*FileStorageContainersItemDriveItemsItemGetActivitiesByIntervalResponse) {
    m := &FileStorageContainersItemDriveItemsItemGetActivitiesByIntervalResponse{
        FileStorageContainersItemDriveItemsItemGetActivitiesByIntervalGetResponse: *NewFileStorageContainersItemDriveItemsItemGetActivitiesByIntervalGetResponse(),
    }
    return m
}
// CreateFileStorageContainersItemDriveItemsItemGetActivitiesByIntervalResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateFileStorageContainersItemDriveItemsItemGetActivitiesByIntervalResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFileStorageContainersItemDriveItemsItemGetActivitiesByIntervalResponse(), nil
}
// Deprecated: This class is obsolete. Use FileStorageContainersItemDriveItemsItemGetActivitiesByIntervalGetResponseable instead.
type FileStorageContainersItemDriveItemsItemGetActivitiesByIntervalResponseable interface {
    FileStorageContainersItemDriveItemsItemGetActivitiesByIntervalGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
