package drives

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthGetResponseable instead.
type ItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthResponse struct {
    ItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthGetResponse
}
// NewItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthResponse instantiates a new ItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthResponse and sets the default values.
func NewItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthResponse()(*ItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthResponse) {
    m := &ItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthResponse{
        ItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthGetResponse: *NewItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthGetResponse(),
    }
    return m
}
// CreateItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthGetResponseable instead.
type ItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthResponseable interface {
    ItemItemsItemWorkbookWorksheetsItemChartsItemImagewithwidthImageWithWidthGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
