package drives

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImagegetResponseable instead.
type ItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImageResponse struct {
    ItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImagegetResponse
}
// NewItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImageResponse instantiates a new ItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImageResponse and sets the default values.
func NewItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImageResponse()(*ItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImageResponse) {
    m := &ItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImageResponse{
        ItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImagegetResponse: *NewItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImagegetResponse(),
    }
    return m
}
// CreateItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImageResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImageResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImageResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImagegetResponseable instead.
type ItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImageResponseable interface {
    ItemItemsItemWorkbookWorksheetsItemChartsItemAtWithIndexImagegetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
