package drives

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageGetResponseable instead.
type ItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse struct {
    ItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageGetResponse
}
// NewItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse instantiates a new ItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse and sets the default values.
func NewItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse()(*ItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse) {
    m := &ItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse{
        ItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageGetResponse: *NewItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageGetResponse(),
    }
    return m
}
// CreateItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageGetResponseable instead.
type ItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageResponseable interface {
    ItemItemsItemWorkbookWorksheetsItemChartsItemwithnameImageGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
