package drives

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageGetResponseable instead.
type ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageResponse struct {
    ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageGetResponse
}
// NewItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageResponse instantiates a new ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageResponse and sets the default values.
func NewItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageResponse()(*ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageResponse) {
    m := &ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageResponse{
        ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageGetResponse: *NewItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageGetResponse(),
    }
    return m
}
// CreateItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageGetResponseable instead.
type ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageResponseable interface {
    ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImageGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
