package drives

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthGetResponseable instead.
type ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthResponse struct {
    ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthGetResponse
}
// NewItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthResponse instantiates a new ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthResponse and sets the default values.
func NewItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthResponse()(*ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthResponse) {
    m := &ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthResponse{
        ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthGetResponse: *NewItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthGetResponse(),
    }
    return m
}
// CreateItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthGetResponseable instead.
type ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthResponseable interface {
    ItemItemsItemWorkbookWorksheetsItemChartsItematwithindexImagewithwidthImageWithWidthGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
