package drives

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightResponse 
// Deprecated: This class is obsolete. Use imageWithWidthWithHeightGetResponse instead.
type ItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightResponse struct {
    ItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightGetResponse
}
// NewItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightResponse instantiates a new ItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightResponse and sets the default values.
func NewItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightResponse()(*ItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightResponse) {
    m := &ItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightResponse{
        ItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightGetResponse: *NewItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightGetResponse(),
    }
    return m
}
// CreateItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightResponse(), nil
}
// ItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightResponseable 
// Deprecated: This class is obsolete. Use imageWithWidthWithHeightGetResponse instead.
type ItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightResponseable interface {
    ItemItemsItemWorkbookWorksheetsItemChartsItemWithNameImageWithWidthWithHeightGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
