package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaGetResponseable instead.
type ItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaResponse struct {
    ItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaGetResponse
}
// NewItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaResponse instantiates a new ItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaResponse and sets the default values.
func NewItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaResponse()(*ItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaResponse) {
    m := &ItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaResponse{
        ItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaGetResponse: *NewItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaGetResponseable instead.
type ItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaResponseable interface {
    ItemCalendargroupsItemCalendarsItemCalendarviewItemInstancesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
