package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserGetResponseable instead.
type ItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse struct {
    ItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserGetResponse
}
// NewItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse instantiates a new ItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse and sets the default values.
func NewItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse()(*ItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse) {
    m := &ItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse{
        ItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserGetResponse: *NewItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserGetResponse(),
    }
    return m
}
// CreateItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserGetResponseable instead.
type ItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserResponseable interface {
    ItemCalendarsItemAllowedcalendarsharingroleswithuserAllowedCalendarSharingRolesWithUserGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
