package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesGetResponseable instead.
type ItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesResponse struct {
    ItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesGetResponse
}
// NewItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesResponse instantiates a new ItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesResponse and sets the default values.
func NewItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesResponse()(*ItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesResponse) {
    m := &ItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesResponse{
        ItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesGetResponse: *NewItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesGetResponse(),
    }
    return m
}
// CreateItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesGetResponseable instead.
type ItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesResponseable interface {
    ItemGetmanagedappdiagnosticstatusesGetManagedAppDiagnosticStatusesGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
