package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsResponse 
// Deprecated: This class is obsolete. Use checkMemberGroupsPostResponse instead.
type ItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsResponse struct {
    ItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsPostResponse
}
// NewItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsResponse instantiates a new ItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsResponse and sets the default values.
func NewItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsResponse()(*ItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsResponse) {
    m := &ItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsResponse{
        ItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsPostResponse: *NewItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsPostResponse(),
    }
    return m
}
// CreateItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsResponse(), nil
}
// ItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsResponseable 
// Deprecated: This class is obsolete. Use checkMemberGroupsPostResponse instead.
type ItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsResponseable interface {
    ItemJoinedTeamsItemPermissionGrantsItemCheckMemberGroupsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
