package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCalendargroupsItemCalendarsItemGetscheduleGetSchedulePostResponseable instead.
type ItemCalendargroupsItemCalendarsItemGetscheduleGetScheduleResponse struct {
    ItemCalendargroupsItemCalendarsItemGetscheduleGetSchedulePostResponse
}
// NewItemCalendargroupsItemCalendarsItemGetscheduleGetScheduleResponse instantiates a new ItemCalendargroupsItemCalendarsItemGetscheduleGetScheduleResponse and sets the default values.
func NewItemCalendargroupsItemCalendarsItemGetscheduleGetScheduleResponse()(*ItemCalendargroupsItemCalendarsItemGetscheduleGetScheduleResponse) {
    m := &ItemCalendargroupsItemCalendarsItemGetscheduleGetScheduleResponse{
        ItemCalendargroupsItemCalendarsItemGetscheduleGetSchedulePostResponse: *NewItemCalendargroupsItemCalendarsItemGetscheduleGetSchedulePostResponse(),
    }
    return m
}
// CreateItemCalendargroupsItemCalendarsItemGetscheduleGetScheduleResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCalendargroupsItemCalendarsItemGetscheduleGetScheduleResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendargroupsItemCalendarsItemGetscheduleGetScheduleResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCalendargroupsItemCalendarsItemGetscheduleGetSchedulePostResponseable instead.
type ItemCalendargroupsItemCalendarsItemGetscheduleGetScheduleResponseable interface {
    ItemCalendargroupsItemCalendarsItemGetscheduleGetSchedulePostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
