package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsResponse 
// Deprecated: This class is obsolete. Use checkMemberObjectsPostResponse instead.
type ItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsResponse struct {
    ItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsPostResponse
}
// NewItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsResponse instantiates a new ItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsResponse and sets the default values.
func NewItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsResponse()(*ItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsResponse) {
    m := &ItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsResponse{
        ItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsPostResponse: *NewItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsPostResponse(),
    }
    return m
}
// CreateItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsResponse(), nil
}
// ItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsResponseable 
// Deprecated: This class is obsolete. Use checkMemberObjectsPostResponse instead.
type ItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsResponseable interface {
    ItemJoinedTeamsItemPermissionGrantsItemCheckMemberObjectsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
