package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresGetResponseable instead.
type ItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresResponse struct {
    ItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresGetResponse
}
// NewItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresResponse instantiates a new ItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresResponse and sets the default values.
func NewItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresResponse()(*ItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresResponse) {
    m := &ItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresResponse{
        ItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresGetResponse: *NewItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresGetResponse(),
    }
    return m
}
// CreateItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresGetResponseable instead.
type ItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresResponseable interface {
    ItemGetmanageddeviceswithappfailuresGetManagedDevicesWithAppFailuresGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
