package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardGetResponseable instead.
type ItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardResponse struct {
    ItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardGetResponse
}
// NewItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardResponse instantiates a new ItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardResponse and sets the default values.
func NewItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardResponse()(*ItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardResponse) {
    m := &ItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardResponse{
        ItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardGetResponse: *NewItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardGetResponse(),
    }
    return m
}
// CreateItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardGetResponseable instead.
type ItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardResponseable interface {
    ItemOutlookSupportedtimezoneswithtimezonestandardSupportedTimeZonesWithTimeZoneStandardGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
