package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeGetResponseable instead.
type ItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeResponse struct {
    ItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeGetResponse
}
// NewItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeResponse instantiates a new ItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeResponse and sets the default values.
func NewItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeResponse()(*ItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeResponse) {
    m := &ItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeResponse{
        ItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeGetResponse: *NewItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeGetResponse(),
    }
    return m
}
// CreateItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeGetResponseable instead.
type ItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeResponseable interface {
    ItemReminderviewwithstartdatetimewithenddatetimeReminderViewWithStartDateTimeWithEndDateTimeGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
