package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesResponse 
// Deprecated: This class is obsolete. Use getAvailableExtensionPropertiesPostResponse instead.
type ItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesResponse struct {
    ItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesPostResponse
}
// NewItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesResponse instantiates a new ItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesResponse and sets the default values.
func NewItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesResponse()(*ItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesResponse) {
    m := &ItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesResponse{
        ItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesPostResponse: *NewItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesPostResponse(),
    }
    return m
}
// CreateItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesResponse(), nil
}
// ItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesResponseable 
// Deprecated: This class is obsolete. Use getAvailableExtensionPropertiesPostResponse instead.
type ItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesResponseable interface {
    ItemJoinedTeamsItemPermissionGrantsGetAvailableExtensionPropertiesPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
