package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsResponse 
// Deprecated: This class is obsolete. Use getMemberObjectsPostResponse instead.
type ItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsResponse struct {
    ItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsPostResponse
}
// NewItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsResponse instantiates a new ItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsResponse and sets the default values.
func NewItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsResponse()(*ItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsResponse) {
    m := &ItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsResponse{
        ItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsPostResponse: *NewItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsPostResponse(),
    }
    return m
}
// CreateItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsResponse(), nil
}
// ItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsResponseable 
// Deprecated: This class is obsolete. Use getMemberObjectsPostResponse instead.
type ItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsResponseable interface {
    ItemJoinedTeamsItemPermissionGrantsItemGetMemberObjectsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
