package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesResponse 
// Deprecated: This class is obsolete. Use getAvailableExtensionPropertiesPostResponse instead.
type ItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesResponse struct {
    ItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesPostResponse
}
// NewItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesResponse instantiates a new ItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesResponse and sets the default values.
func NewItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesResponse()(*ItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesResponse) {
    m := &ItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesResponse{
        ItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesPostResponse: *NewItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesPostResponse(),
    }
    return m
}
// CreateItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesResponse(), nil
}
// ItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesResponseable 
// Deprecated: This class is obsolete. Use getAvailableExtensionPropertiesPostResponse instead.
type ItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesResponseable interface {
    ItemChatsItemPermissionGrantsGetAvailableExtensionPropertiesPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
