package users

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaGetResponseable instead.
type ItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaResponse struct {
    ItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaGetResponse
}
// NewItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaResponse instantiates a new ItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaResponse and sets the default values.
func NewItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaResponse()(*ItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaResponse) {
    m := &ItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaResponse{
        ItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaGetResponse: *NewItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaGetResponse(),
    }
    return m
}
// CreateItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaGetResponseable instead.
type ItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaResponseable interface {
    ItemCalendargroupsItemCalendarsItemEventsItemInstancesDeltaGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
