package communications

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use CallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeGetResponseable instead.
type CallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeResponse struct {
    CallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeGetResponse
}
// NewCallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeResponse instantiates a new CallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeResponse and sets the default values.
func NewCallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeResponse()(*CallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeResponse) {
    m := &CallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeResponse{
        CallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeGetResponse: *NewCallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeGetResponse(),
    }
    return m
}
// CreateCallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeResponse(), nil
}
// Deprecated: This class is obsolete. Use CallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeGetResponseable instead.
type CallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeResponseable interface {
    CallrecordsMicrosoftgraphcallrecordsgetpstncallswithfromdatetimewithtodatetimeGetPstnCallsWithFromDateTimeWithToDateTimeGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
