package communications

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use CallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeGetResponseable instead.
type CallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeResponse struct {
    CallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeGetResponse
}
// NewCallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeResponse instantiates a new CallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeResponse and sets the default values.
func NewCallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeResponse()(*CallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeResponse) {
    m := &CallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeResponse{
        CallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeGetResponse: *NewCallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeGetResponse(),
    }
    return m
}
// CreateCallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeResponse(), nil
}
// Deprecated: This class is obsolete. Use CallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeGetResponseable instead.
type CallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeResponseable interface {
    CallrecordsMicrosoftgraphcallrecordsgetdirectroutingcallswithfromdatetimewithtodatetimeGetDirectRoutingCallsWithFromDateTimeWithToDateTimeGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
