package sites

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponseable instead.
type ItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse struct {
    ItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponse
}
// NewItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse instantiates a new ItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse and sets the default values.
func NewItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse()(*ItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse) {
    m := &ItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse{
        ItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponse: *NewItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponse(),
    }
    return m
}
// CreateItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponseable instead.
type ItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalResponseable interface {
    ItemListsItemItemsItemGetactivitiesbyintervalGetActivitiesByIntervalGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
