package sites

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponseable instead.
type ItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse struct {
    ItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponse
}
// NewItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse instantiates a new ItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse and sets the default values.
func NewItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse()(*ItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse) {
    m := &ItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse{
        ItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponse: *NewItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponse(),
    }
    return m
}
// CreateItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponseable instead.
type ItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesResponseable interface {
    ItemListsItemContenttypesGetcompatiblehubcontenttypesGetCompatibleHubContentTypesGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
