package sites

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdGetResponseable instead.
type ItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse struct {
    ItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdGetResponse
}
// NewItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse instantiates a new ItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse and sets the default values.
func NewItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse()(*ItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse) {
    m := &ItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse{
        ItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdGetResponse: *NewItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdGetResponse(),
    }
    return m
}
// CreateItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdGetResponseable instead.
type ItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdResponseable interface {
    ItemGetbypathwithpathGetapplicablecontenttypesforlistwithlistidGetApplicableContentTypesForListWithListIdGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
