package identity

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a "github.com/microsoftgraph/msgraph-sdk-go/models/odataerrors"
)

// AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder casts the previous resource to onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp.
type AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewAuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilderInternal instantiates a new AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder and sets the default values.
func NewAuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder) {
    m := &AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/identity/authenticationEventsFlows/{authenticationEventsFlow%2Did}/graph.externalUsersSelfServiceSignUpEventsFlow/onAuthenticationMethodLoadStart/graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp", pathParameters),
    }
    return m
}
// NewAuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder instantiates a new AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder and sets the default values.
func NewAuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewAuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get the items of type microsoft.graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp in the microsoft.graph.onAuthenticationMethodLoadStartHandler collection
// returns a []byte when successful
// returns a ODataError error when the service returns a 4XX or 5XX status code
func (m *AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder) Get(ctx context.Context, requestConfiguration *AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilderGetRequestConfiguration)([]byte, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ia572726a95efa92ddd544552cd950653dc691023836923576b2f4bf716cf204a.CreateODataErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendPrimitive(ctx, requestInfo, "[]byte", errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.([]byte), nil
}
// IdentityProviders provides operations to manage the identityProviders property of the microsoft.graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp entity.
// returns a *AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupIdentityprovidersIdentityProvidersRequestBuilder when successful
func (m *AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder) IdentityProviders()(*AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupIdentityprovidersIdentityProvidersRequestBuilder) {
    return NewAuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupIdentityprovidersIdentityProvidersRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// ToGetRequestInformation get the items of type microsoft.graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp in the microsoft.graph.onAuthenticationMethodLoadStartHandler collection
// returns a *RequestInformation when successful
func (m *AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder when successful
func (m *AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder) WithUrl(rawUrl string)(*AuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder) {
    return NewAuthenticationeventsflowsItemGraphexternalusersselfservicesignupeventsflowOnauthenticationmethodloadstartGraphonauthenticationmethodloadstartexternalusersselfservicesignupGraphOnAuthenticationMethodLoadStartExternalUsersSelfServiceSignUpRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
