package identity

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use IdentityprovidersAvailableprovidertypesAvailableProviderTypesGetResponseable instead.
type IdentityprovidersAvailableprovidertypesAvailableProviderTypesResponse struct {
    IdentityprovidersAvailableprovidertypesAvailableProviderTypesGetResponse
}
// NewIdentityprovidersAvailableprovidertypesAvailableProviderTypesResponse instantiates a new IdentityprovidersAvailableprovidertypesAvailableProviderTypesResponse and sets the default values.
func NewIdentityprovidersAvailableprovidertypesAvailableProviderTypesResponse()(*IdentityprovidersAvailableprovidertypesAvailableProviderTypesResponse) {
    m := &IdentityprovidersAvailableprovidertypesAvailableProviderTypesResponse{
        IdentityprovidersAvailableprovidertypesAvailableProviderTypesGetResponse: *NewIdentityprovidersAvailableprovidertypesAvailableProviderTypesGetResponse(),
    }
    return m
}
// CreateIdentityprovidersAvailableprovidertypesAvailableProviderTypesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIdentityprovidersAvailableprovidertypesAvailableProviderTypesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewIdentityprovidersAvailableprovidertypesAvailableProviderTypesResponse(), nil
}
// Deprecated: This class is obsolete. Use IdentityprovidersAvailableprovidertypesAvailableProviderTypesGetResponseable instead.
type IdentityprovidersAvailableprovidertypesAvailableProviderTypesResponseable interface {
    IdentityprovidersAvailableprovidertypesAvailableProviderTypesGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
