package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestGetResponseable instead.
type ApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestResponse struct {
    ApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestGetResponse
}
// NewApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestResponse instantiates a new ApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestResponse and sets the default values.
func NewApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestResponse()(*ApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestResponse) {
    m := &ApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestResponse{
        ApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestGetResponse: *NewApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestGetResponse(),
    }
    return m
}
// CreateApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestResponse(), nil
}
// Deprecated: This class is obsolete. Use ApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestGetResponseable instead.
type ApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestResponseable interface {
    ApplepushnotificationcertificateDownloadapplepushnotificationcertificatesigningrequestDownloadApplePushNotificationCertificateSigningRequestGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
