package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use GeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeGetResponseable instead.
type GeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeResponse struct {
    GeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeGetResponse
}
// NewGeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeResponse instantiates a new GeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeResponse and sets the default values.
func NewGeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeResponse()(*GeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeResponse) {
    m := &GeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeResponse{
        GeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeGetResponse: *NewGeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeGetResponse(),
    }
    return m
}
// CreateGeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeResponse(), nil
}
// Deprecated: This class is obsolete. Use GeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeGetResponseable instead.
type GeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeResponseable interface {
    GeteffectivepermissionswithscopeGetEffectivePermissionsWithScopeGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
