package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlpostResponseable instead.
type ManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlResponse struct {
    ManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlpostResponse
}
// NewManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlResponse instantiates a new ManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlResponse and sets the default values.
func NewManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlResponse()(*ManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlResponse) {
    m := &ManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlResponse{
        ManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlpostResponse: *NewManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlpostResponse(),
    }
    return m
}
// CreateManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlResponse(), nil
}
// Deprecated: This class is obsolete. Use ManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlpostResponseable instead.
type ManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlResponseable interface {
    ManagedDevicesItemLogCollectionRequestsItemCreateDownloadUrlpostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
