package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlPostResponseable instead.
type ManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlResponse struct {
    ManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlPostResponse
}
// NewManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlResponse instantiates a new ManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlResponse and sets the default values.
func NewManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlResponse()(*ManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlResponse) {
    m := &ManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlResponse{
        ManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlPostResponse: *NewManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlPostResponse(),
    }
    return m
}
// CreateManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlResponse(), nil
}
// Deprecated: This class is obsolete. Use ManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlPostResponseable instead.
type ManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlResponseable interface {
    ManageddevicesItemLogcollectionrequestsItemCreatedownloadurlCreateDownloadUrlPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
