package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use UserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByGetResponseable instead.
type UserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByResponse struct {
    UserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByGetResponse
}
// NewUserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByResponse instantiates a new UserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByResponse and sets the default values.
func NewUserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByResponse()(*UserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByResponse) {
    m := &UserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByResponse{
        UserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByGetResponse: *NewUserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByGetResponse(),
    }
    return m
}
// CreateUserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateUserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewUserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByResponse(), nil
}
// Deprecated: This class is obsolete. Use UserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByGetResponseable instead.
type UserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    UserexperienceanalyticsdeviceperformanceSummarizedeviceperformancedeviceswithsummarizebySummarizeDevicePerformanceDevicesWithSummarizeByGetResponseable
}
