package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use VerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameGetResponseable instead.
type VerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameResponse struct {
    VerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameGetResponse
}
// NewVerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameResponse instantiates a new VerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameResponse and sets the default values.
func NewVerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameResponse()(*VerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameResponse) {
    m := &VerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameResponse{
        VerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameGetResponse: *NewVerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameGetResponse(),
    }
    return m
}
// CreateVerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewVerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameResponse(), nil
}
// Deprecated: This class is obsolete. Use VerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameGetResponseable instead.
type VerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    VerifywindowsenrollmentautodiscoverywithdomainnameVerifyWindowsEnrollmentAutoDiscoveryWithDomainNameGetResponseable
}
