package devicemanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use VirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesGetResponseable instead.
type VirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesResponse struct {
    VirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesGetResponse
}
// NewVirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesResponse instantiates a new VirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesResponse and sets the default values.
func NewVirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesResponse()(*VirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesResponse) {
    m := &VirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesResponse{
        VirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesGetResponse: *NewVirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesGetResponse(),
    }
    return m
}
// CreateVirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewVirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesResponse(), nil
}
// Deprecated: This class is obsolete. Use VirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesGetResponseable instead.
type VirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    VirtualendpointAuditeventsGetauditactivitytypesGetAuditActivityTypesGetResponseable
}
