package deviceappmanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationgetResponseable instead.
type ManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationResponse struct {
    ManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationgetResponse
}
// NewManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationResponse instantiates a new ManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationResponse and sets the default values.
func NewManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationResponse()(*ManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationResponse) {
    m := &ManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationResponse{
        ManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationgetResponse: *NewManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationgetResponse(),
    }
    return m
}
// CreateManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationResponse(), nil
}
// Deprecated: This class is obsolete. Use ManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationgetResponseable instead.
type ManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationResponseable interface {
    ManagedAppRegistrationsGetUserIdsWithFlaggedAppRegistrationgetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
