package deviceappmanagement

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationGetResponseable instead.
type ManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationResponse struct {
    ManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationGetResponse
}
// NewManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationResponse instantiates a new ManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationResponse and sets the default values.
func NewManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationResponse()(*ManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationResponse) {
    m := &ManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationResponse{
        ManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationGetResponse: *NewManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationGetResponse(),
    }
    return m
}
// CreateManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationResponse(), nil
}
// Deprecated: This class is obsolete. Use ManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationGetResponseable instead.
type ManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationResponseable interface {
    ManagedappregistrationsGetuseridswithflaggedappregistrationGetUserIdsWithFlaggedAppRegistrationGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
