package policies

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// FeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesResponse 
// Deprecated: This class is obsolete. Use getAvailableExtensionPropertiesPostResponse instead.
type FeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesResponse struct {
    FeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesPostResponse
}
// NewFeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesResponse instantiates a new FeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesResponse and sets the default values.
func NewFeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesResponse()(*FeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesResponse) {
    m := &FeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesResponse{
        FeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesPostResponse: *NewFeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesPostResponse(),
    }
    return m
}
// CreateFeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
func CreateFeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewFeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesResponse(), nil
}
// FeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesResponseable 
// Deprecated: This class is obsolete. Use getAvailableExtensionPropertiesPostResponse instead.
type FeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesResponseable interface {
    FeatureRolloutPoliciesItemAppliesToGetAvailableExtensionPropertiesPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
