// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CopilotAdminCatalog struct {
    Entity
}
// NewCopilotAdminCatalog instantiates a new CopilotAdminCatalog and sets the default values.
func NewCopilotAdminCatalog()(*CopilotAdminCatalog) {
    m := &CopilotAdminCatalog{
        Entity: *NewEntity(),
    }
    return m
}
// CreateCopilotAdminCatalogFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCopilotAdminCatalogFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCopilotAdminCatalog(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CopilotAdminCatalog) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.Entity.GetFieldDeserializers()
    res["packages"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateCopilotPackageDetailFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]CopilotPackageDetailable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(CopilotPackageDetailable)
                }
            }
            m.SetPackages(res)
        }
        return nil
    }
    return res
}
// GetPackages gets the packages property value. The packages property
// returns a []CopilotPackageDetailable when successful
func (m *CopilotAdminCatalog) GetPackages()([]CopilotPackageDetailable) {
    val, err := m.GetBackingStore().Get("packages")
    if err != nil {
        panic(err)
    }
    if val != nil {
        return val.([]CopilotPackageDetailable)
    }
    return nil
}
// Serialize serializes information the current object
func (m *CopilotAdminCatalog) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.Entity.Serialize(writer)
    if err != nil {
        return err
    }
    if m.GetPackages() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetPackages()))
        for i, v := range m.GetPackages() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err = writer.WriteCollectionOfObjectValues("packages", cast)
        if err != nil {
            return err
        }
    }
    return nil
}
// SetPackages sets the packages property value. The packages property
func (m *CopilotAdminCatalog) SetPackages(value []CopilotPackageDetailable)() {
    err := m.GetBackingStore().Set("packages", value)
    if err != nil {
        panic(err)
    }
}
type CopilotAdminCatalogable interface {
    Entityable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPackages()([]CopilotPackageDetailable)
    SetPackages(value []CopilotPackageDetailable)()
}
