// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type OnlineMeetingType int

const (
    ADHOC_ONLINEMEETINGTYPE OnlineMeetingType = iota
    SCHEDULED_ONLINEMEETINGTYPE
    RECURRING_ONLINEMEETINGTYPE
    BROADCAST_ONLINEMEETINGTYPE
    MEETNOW_ONLINEMEETINGTYPE
    UNKNOWNFUTUREVALUE_ONLINEMEETINGTYPE
)

func (i OnlineMeetingType) String() string {
    return []string{"adhoc", "scheduled", "recurring", "broadcast", "meetnow", "unknownFutureValue"}[i]
}
func ParseOnlineMeetingType(v string) (any, error) {
    result := ADHOC_ONLINEMEETINGTYPE
    switch v {
        case "adhoc":
            result = ADHOC_ONLINEMEETINGTYPE
        case "scheduled":
            result = SCHEDULED_ONLINEMEETINGTYPE
        case "recurring":
            result = RECURRING_ONLINEMEETINGTYPE
        case "broadcast":
            result = BROADCAST_ONLINEMEETINGTYPE
        case "meetnow":
            result = MEETNOW_ONLINEMEETINGTYPE
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_ONLINEMEETINGTYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeOnlineMeetingType(values []OnlineMeetingType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i OnlineMeetingType) isMultiValue() bool {
    return false
}
