// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type PciVersion int

const (
    NONE_PCIVERSION PciVersion = iota
    V3_2_1_PCIVERSION
    V4_PCIVERSION
    NOTSUPPORTED_PCIVERSION
    UNKNOWNFUTUREVALUE_PCIVERSION
)

func (i PciVersion) String() string {
    return []string{"none", "v3_2_1", "v4", "notSupported", "unknownFutureValue"}[i]
}
func ParsePciVersion(v string) (any, error) {
    result := NONE_PCIVERSION
    switch v {
        case "none":
            result = NONE_PCIVERSION
        case "v3_2_1":
            result = V3_2_1_PCIVERSION
        case "v4":
            result = V4_PCIVERSION
        case "notSupported":
            result = NOTSUPPORTED_PCIVERSION
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_PCIVERSION
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializePciVersion(values []PciVersion) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i PciVersion) isMultiValue() bool {
    return false
}
