// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type VerifiedIdUsageConfigurationPurpose int

const (
    RECOVERY_VERIFIEDIDUSAGECONFIGURATIONPURPOSE VerifiedIdUsageConfigurationPurpose = iota
    ONBOARDING_VERIFIEDIDUSAGECONFIGURATIONPURPOSE
    ALL_VERIFIEDIDUSAGECONFIGURATIONPURPOSE
    UNKNOWNFUTUREVALUE_VERIFIEDIDUSAGECONFIGURATIONPURPOSE
)

func (i VerifiedIdUsageConfigurationPurpose) String() string {
    return []string{"recovery", "onboarding", "all", "unknownFutureValue"}[i]
}
func ParseVerifiedIdUsageConfigurationPurpose(v string) (any, error) {
    result := RECOVERY_VERIFIEDIDUSAGECONFIGURATIONPURPOSE
    switch v {
        case "recovery":
            result = RECOVERY_VERIFIEDIDUSAGECONFIGURATIONPURPOSE
        case "onboarding":
            result = ONBOARDING_VERIFIEDIDUSAGECONFIGURATIONPURPOSE
        case "all":
            result = ALL_VERIFIEDIDUSAGECONFIGURATIONPURPOSE
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_VERIFIEDIDUSAGECONFIGURATIONPURPOSE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeVerifiedIdUsageConfigurationPurpose(values []VerifiedIdUsageConfigurationPurpose) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i VerifiedIdUsageConfigurationPurpose) isMultiValue() bool {
    return false
}
